### ISSUE TITLE
Missing package blob on upload causes 500

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#2857]
If a package is uploaded, and we return 500 (for example because of #2856), then subsequent retries of the request also returns 500 as we fail to handle the 404 from GCS.

This should be a 400 saying that the user didn't upload the file to GCS, or that previous attempt to process it failed, and ask that we grep through logs for the blob id, which is the UUID of the file.

```
pub.cloud_repository: An error occured while streaming tarball to FS.

Error:
    DetailedApiRequestError(status: 404, message: No error details. HTTP status was: 404.)

Stack:
    #0      _validateResponse (package:_discoveryapis_commons/src/clients.dart:879:5)
    <asynchronous suspension>
    #1      ApiRequester.request (package:_discoveryapis_commons/src/clients.dart:69:22)
    <asynchronous suspension>
    #2      ObjectsResourceApi.get (package:googleapis/storage/v1.dart:2832:32)
    #3      _BucketImpl.read (package:gcloud/src/storage_impl.dart:222:47)
    <asynchronous suspension>
    #4      TarballStorage.readTempObject (package:pub_dartlang_org/package/backend.dart:1075:14)
    #5      GCloudPackageRepository.finishAsyncUpload.<anonymous closure> (package:pub_dartlang_org/package/backend.dart:569:38)
    <asynchronous suspension>
    #6      withTempDirectory.<anonymous closure> (package:pub_dartlang_org/shared/utils.dart:44:16)
    #7      StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
    #8      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #9      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
    #10     _rootRunUnary (dart:async/zone.dart:1132:38)
    #11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
    #12     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
    #13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
    #14     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
    #15     Future._completeWithValue (dart:async/future_impl.dart:483:5)
    #16     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
    #17     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #18     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #19     _rootRun (dart:async/zone.dart:1124:13)
    #20     _CustomZone.run (dart:async/zone.dart:1021:19)
    #21     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
    #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
    #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
    #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
    #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
    #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

**Comment by jonasfj** [comment]
This can also happen if the transaction failed for some reason.
