### ISSUE TITLE
504: DEADLINE_EXCEEDED is frequent in dartdoc service

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3190]
Based on [GCS docs](https://cloud.google.com/apis/design/errors#handling_errors) it appears that 504 is deadline exceeded. This might be worth investigating.

What files causes this? What deadline are we setting?

Looking at logs this appears in more than just the most recent deployment.

Stack traces looks like:
```
"pub.job: dartdoc job error persist_theme 1.5.1

Error:
    DetailedApiRequestError(status: 504, message: )

Stack:
    #0      _validateResponse (package:_discoveryapis_commons/src/clients.dart:852:9)
    <asynchronous suspension>
    #1      ApiRequester.request (package:_discoveryapis_commons/src/clients.dart:74:22)
    <asynchronous suspension>
    #2      ObjectsResourceApi.delete (package:googleapis/storage/v1.dart:2990:32)
    #3      _BucketImpl.delete (package:gcloud/src/storage_impl.dart:235:25)
    #4      deleteFromBucket (package:pub_dev/shared/storage.dart:36:18)
    <asynchronous suspension>
    #5      DartdocBackend._deleteAllWithPrefix.<anonymous closure> (package:pub_dev/dartdoc/backend.dart:381:33)
    #6      Pool.withResource (package:pool/pool.dart:127:28)
    <asynchronous suspension>
    #7      DartdocBackend._deleteAllWithPrefix (package:pub_dev/dartdoc/backend.dart:381:14)
    #8      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
    #9      StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
    #10     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #11     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
    #12     _rootRunUnary (dart:async/zone.dart:1134:38)
    #13     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
    #14     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
    #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
    #16     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
    #17     Future._completeWithValue (dart:async/future_impl.dart:524:5)
    #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
    #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
    #20     ApiRequester.request (package:_discoveryapis_commons/src/clients.dart)
    #21     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
    #22     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
    #23     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #24     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
    #25     _rootRunUnary (dart:async/zone.dart:1134:38)
    #26     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
    #27     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
    #28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
    #29     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
    #30     Future._complete (dart:async/future_impl.dart:514:7)
    #31     Stream.join.<anonymous closure> (dart:async/stream.dart:844:18)
    #32     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #33     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #34     _rootRun (dart:async/zone.dart:1122:38)
    #35     _CustomZone.run (dart:async/zone.dart:1023:19)
    #36     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
    #37     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
    #38     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
    #39     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
    #40     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:98:11)
    #41     _EventSinkWrapper.close (dart:async/stream_transformers.dart:25:11)
    #42     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
    #43     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:302:20)
    #44     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
    #45     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:143:24)
    #46     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #47     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #48     _rootRun (dart:async/zone.dart:1122:38)
    #49     _CustomZone.run (dart:async/zone.dart:1023:19)
    #50     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
    #51     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
    #52     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
    #53     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
    #54     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:108:10)
    #55     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:174:13)
    #56     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #57     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #58     _rootRun (dart:async/zone.dart:1122:38)
    #59     _CustomZone.run (dart:async/zone.dart:1023:19)
    #60     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
    #61     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
    #62     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
    #63     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
    #64     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:108:10)
    #65     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:174:13)
    #66     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #67     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #68     _rootRun (dart:async/zone.dart:1122:38)
    #69     _CustomZone.run (dart:async/zone.dart:1023:19)
    #70     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
    #71     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
    #72     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
    #73     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
    #74     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:774:19)
    #75     _StreamController._closeUnchecked (dart:async/stream_controller.dart:631:7)
    #76     _StreamController.close (dart:async/stream_controller.dart:624:5)
    #77     _HttpParser._closeIncoming (dart:_http/http_parser.dart:1039:23)
    #78     _HttpParser._doParse (dart:_http/http_parser.dart:777:15)
    #79     _HttpParser._parse (dart:_http/http_parser.dart:320:7)
    #80     _HttpParser._onData (dart:_http/http_parser.dart:812:5)
    #81     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
    #82     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #83     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
    #84     _rootRunUnary (dart:async/zone.dart:1134:38)
    #85     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
    #86     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
    #87     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
    #88     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
    #89     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
    #90     _StreamController._add (dart:async/stream_controller.dart:642:7)
    #91     _StreamController.add (dart:async/stream_controller.dart:588:5)
    #92     _Socket._onData (dart:io-patch/socket_patch.dart:1831:41)
    #93     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
    #94     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #95     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
    #96     _rootRunUnary (dart:async/zone.dart:1134:38)
    #97     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
    #98     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
    #99     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
    #100    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
    #101    _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
    #102    _StreamController._add (dart:async/stream_controller.dart:642:7)
    #103    _StreamController.add (dart:async/stream_controller.dart:588:5)
    #104    _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1018:19)
    #105    StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #106    StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #107    _rootRun (dart:async/zone.dart:1122:38)
    #108    _CustomZone.run (dart:async/zone.dart:1023:19)
    #109    _CustomZone.runGuarded (dart:async/zone.dart:925:7)
    #110    _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
    #111    StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #112    StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #113    _rootRun (dart:async/zone.dart:1126:13)
    #114    _CustomZone.run (dart:async/zone.dart:1023:19)
    #115    _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
    #116    Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
    #117    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
    #118    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
    #119    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by isoos** [comment]
This should be handled by the retrying storage client.
