### ISSUE TITLE
Possible regression -- Unable to read entry

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3419]
```
"pub.dartdoc.backend: Unable to read entry: passwordwidget/0.1.3/entry/aa8078cd-1c49-46b3-b279-30ed3d663ea5.json.

Error:
    DetailedApiRequestError(status: 504, message: No error details. HTTP status was: 504.)

Stack:
    #0      _validateResponse (package:_discoveryapis_commons/src/clients.dart:856:5)
    <asynchronous suspension>
    #1      ApiRequester.request (package:_discoveryapis_commons/src/clients.dart:74:22)
    <asynchronous suspension>
    #2      ObjectsResourceApi.get (package:googleapis/storage/v1.dart:3115:32)
    #3      _BucketImpl.read (package:gcloud/src/storage_impl.dart:222:47)
    <asynchronous suspension>
    #4      DartdocBackend._listEntries.<anonymous closure> (package:pub_dev/dartdoc/backend.dart:387:61)
    <asynchronous suspension>
    #5      RetryOptions.retry (package:retry/retry.dart:130:24)
    <asynchronous suspension>
    #6      retry (package:retry/retry.dart:187:7)
    #7      DartdocBackend._listEntries (package:pub_dev/dartdoc/backend.dart:379:12)
    <asynchronous suspension>
    #8      DartdocBackend.getServingEntry.loadVersion (package:pub_dev/dartdoc/backend.dart:182:17)
    <asynchronous suspension>
    #9      DartdocBackend.getServingEntry (package:pub_dev/dartdoc/backend.dart:205:32)
    <asynchronous suspension>
    #10     DartdocClient.getTextContent (package:pub_dev/dartdoc/dartdoc_client.dart:64:12)
    <asynchronous suspension>
    #11     SearchBackend.loadDocument (package:pub_dev/search/backend.dart:87:48)
    <asynchronous suspension>
    #12     IndexUpdater.runTask (package:pub_dev/search/updater.dart:151:39)
    <asynchronous suspension>
    #13     TaskScheduler.run.runTask (package:pub_dev/shared/task_scheduler.dart:67:26)
    <asynchronous suspension>
    #14     TaskScheduler.run (package:pub_dev/shared/task_scheduler.dart:101:20)
    <asynchronous suspension>
    #15     IndexUpdater.runScheduler (package:pub_dev/search/updater.dart:121:15)
    #16     _main.<anonymous closure>.<anonymous closure> (package:pub_dev/service/entrypoint/search.dart:76:20)
    <asynchronous suspension>
    #17     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #18     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #19     _rootRun (dart:async/zone.dart:1122:38)
    #20     _CustomZone.run (dart:async/zone.dart:1023:19)
    #21     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
    #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
    #23     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #24     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #25     _rootRun (dart:async/zone.dart:1126:13)
    #26     _CustomZone.run (dart:async/zone.dart:1023:19)
    #27     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
    #28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
    #29     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
    #30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
    #31     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:393:30)
    #32     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
    #33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by jonasfj** [comment]
@isoos, I think this is a possible regression.

**Comment by isoos** [comment]
I think this is more of a temporary issue (504: gateway timeout). The dartdoc files being generated, uploaded (+ old ones deleted) may hit the rate limit.

**Comment by isoos** [comment]
This exception should be fixed, as we are now reading the entry from Datastore.
