### ISSUE TITLE
Exception: Couldn't find a pubspec.yaml in /.

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3430]
The problem seems to be `firebase_document_repository` version 0.0.1, from logs found using error reporting:
```
pub.analyzer.pana: Failed (v0.13.5) - firebase_document_repository/0.0.1

Error:
    Exception: Couldn't find a pubspec.yaml in /.

Stack:
    #0      new Pubspec.parseFromDir (package:pana/src/pubspec.dart:23:7)
    #1      _PubspecCache.pubspecOfPackage.<anonymous closure> (package:pana/src/tag_detection.dart:268:22)
    #2      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
    #3      _PubspecCache.pubspecOfPackage (package:pana/src/tag_detection.dart:267:26)
    #4      _DeclaredFlutterPlatformDetector._declaredFlutterPlatforms.<anonymous closure> (package:pana/src/tag_detection.dart:429:36)
    #5      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
    #6      _DeclaredFlutterPlatformDetector._declaredFlutterPlatforms (package:pana/src/tag_detection.dart:427:35)
    #7      new _PlatformViolationFinder.<anonymous closure> (package:pana/src/tag_detection.dart:465:20)
    #8      _PathFinder.findPath (package:pana/src/tag_detection.dart:123:11)
    #9      _PlatformViolationFinder._findPlatformViolation (package:pana/src/tag_detection.dart:470:59)
    #10     Tagger.flutterPlatformTags (package:pana/src/tag_detection.dart:653:44)
    #11     PackageAnalyzer._inspect (package:pana/src/package_analyzer.dart:332:26)
    #12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
    #13     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
    #14     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #15     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
    #16     _rootRunUnary (dart:async/zone.dart:1134:38)
    #17     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
    #18     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
    #19     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
    #20     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
    #21     Future._completeWithValue (dart:async/future_impl.dart:524:5)
    #22     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
    #23     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
    #24     PackageAnalyzer._pkgAnalyze (package:pana/src/package_analyzer.dart)
    #25     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
    #26     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
    #27     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #28     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
    #29     _rootRunUnary (dart:async/zone.dart:1134:38)
    #30     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
    #31     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
    #32     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
    #33     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
    #34     Future._completeWithValue (dart:async/future_impl.dart:524:5)
    #35     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
    #36     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
    #37     ToolEnvironment.runAnalyzer (package:pana/src/sdk_env.dart)
    #38     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
    #39     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
    #40     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #41     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
    #42     _rootRunUnary (dart:async/zone.dart:1134:38)
    #43     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
    #44     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
    #45     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
    #46     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
    #47     Future._completeWithValue (dart:async/future_impl.dart:524:5)
    #48     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
    #49     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #50     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #51     _rootRun (dart:async/zone.dart:1126:13)
    #52     _CustomZone.run (dart:async/zone.dart:1023:19)
    #53     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
    #54     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
    #55     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
    #56     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
    #57     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
    #58     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5) 
```

**Comment by sigurdm** [comment]
There seems to be a file: import in lib/core/external_repository.dart that chokes up our path resolution.
``` dart
import 'file:///C:/Users/Wagner%20Silvestre/StudioProjects/akitem_client_app/lib/clientapp/firebase/repository/core/document_repository.dart';
```
