### ISSUE TITLE
Tried calling: any(Closure: (CodeProblem) => bool)

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3457]
Production error in analyzer version `20200324t171808-all`.

**stack trace** from logs:
```
pub.analyzer.pana: Failed (v0.13.6) - built_redux/7.5.10

Error:
    NoSuchMethodError: The method 'any' was called on null.
    Receiver: null
    Tried calling: any(Closure: (CodeProblem) => bool)

Stack:
    #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
    #1      PackageAnalyzer._inspect (package:pana/src/package_analyzer.dart:335:26)
    <asynchronous suspension>
    #2      PackageAnalyzer.inspectPackage.<anonymous closure> (package:pana/src/package_analyzer.dart:95:22)
    <asynchronous suspension>
    #3      _rootRun (dart:async/zone.dart:1126:13)
    #4      _CustomZone.run (dart:async/zone.dart:1023:19)
    #5      _runZoned (dart:async/zone.dart:1518:10)
    #6      runZoned (dart:async/zone.dart:1465:12)
    #7      withLogger (package:pana/src/logging.dart:13:70)
    #8      PackageAnalyzer.inspectPackage (package:pana/src/package_analyzer.dart:81:12)
    #9      AnalyzerJobProcessor.process.analyze (package:pub_dev/analyzer/pana_runner.dart:75:31)
    <asynchronous suspension>
    #10     AnalyzerJobProcessor.process (package:pub_dev/analyzer/pana_runner.dart:97:36)
    <asynchronous suspension>
    #11     JobProcessor.run (package:pub_dev/job/job.dart:55:28)
    <asynchronous suspension>
    #12     JobMaintenance.run (package:pub_dev/job/job.dart:95:18)
    #13     _workerMain.<anonymous closure> (package:pub_dev/service/entrypoint/analyzer.dart:94:26)
    #14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
    #15     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
    #16     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #17     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
    #18     _rootRunUnary (dart:async/zone.dart:1134:38)
    #19     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
    #20     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
    #21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
    #22     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
    #23     Future._completeWithValue (dart:async/future_impl.dart:524:5)
    #24     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
    #25     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
    #26     PopularityStorage.init (package:pub_dev/shared/popularity_storage.dart)
    #27     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
    #28     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
    #29     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #30     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
    #31     _rootRunUnary (dart:async/zone.dart:1134:38)
    #32     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
    #33     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
    #34     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
    #35     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
    #36     Future._completeWithValue (dart:async/future_impl.dart:524:5)
    #37     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
    #38     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
    #39     PopularityStorage.fetch (package:pub_dev/shared/popularity_storage.dart)
    #40     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
    #41     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
    #42     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #43     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
    #44     _rootRunUnary (dart:async/zone.dart:1134:38)
    #45     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
    #46     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
    #47     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
    #48     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
    #49     Future._complete (dart:async/future_impl.dart:514:7)
    #50     Stream.single.<anonymous closure> (dart:async/stream.dart:1334:20)
    #51     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #52     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #53     _rootRun (dart:async/zone.dart:1122:38)
    #54     _CustomZone.run (dart:async/zone.dart:1023:19)
    #55     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
    #56     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
    #57     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
    #58     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
    #59     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:98:11)
    #60     _EventSinkWrapper.close (dart:async/stream_transformers.dart:25:11)
    #61     _JsonStringDecoderSink.close (dart:convert-patch/convert_patch.dart:1492:11)
    #62     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
    #63     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:143:24)
    #64     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #65     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #66     _rootRun (dart:async/zone.dart:1122:38)
    #67     _CustomZone.run (dart:async/zone.dart:1023:19)
    #68     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
    #69     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
    #70     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
    #71     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
    #72     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:98:11)
    #73     _EventSinkWrapper.close (dart:async/stream_transformers.dart:25:11)
    #74     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
    #75     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:302:20)
    #76     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
    #77     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:143:24)
    #78     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #79     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #80     _rootRun (dart:async/zone.dart:1122:38)
    #81     _CustomZone.run (dart:async/zone.dart:1023:19)
    #82     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
    #83     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
    #84     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
    #85     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
    #86     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:98:11)
    #87     _EventSinkWrapper.close (dart:async/stream_transformers.dart:25:11)
    #88     _ByteAdapterSink.close (dart:convert/byte_conversion.dart:64:11)
    #89     _FilterSink.close (dart:io/data_transformer.dart:639:11)
    #90     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
    #91     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:143:24)
    #92     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #93     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #94     _rootRun (dart:async/zone.dart:1122:38)
    #95     _CustomZone.run (dart:async/zone.dart:1023:19)
    #96     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
    #97     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
    #98     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
    #99     _DelayedDone.perform (dart:async/stream_impl.dart:612:14)
    #100    _StreamImplEvents.handleNext (dart:async/stream_impl.dart:709:11)
    #101    _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:669:7)
    #102    StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #103    StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #104    _rootRun (dart:async/zone.dart:1122:38)
    #105    _CustomZone.run (dart:async/zone.dart:1023:19)
    #106    _CustomZone.runGuarded (dart:async/zone.dart:925:7)
    #107    _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
    #108    StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #109    StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #110    _rootRun (dart:async/zone.dart:1126:13)
    #111    _CustomZone.run (dart:async/zone.dart:1023:19)
    #112    _CustomZone.runGuarded (dart:async/zone.dart:925:7)
    #113    _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
    #114    _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
    #115    _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
    #116    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:393:30)
    #117    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
    #118    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by jonasfj** [comment]
So far all errors are related to `built_redux` version `7.5.10`.
