### ISSUE TITLE
analysis_options causes issue for dartdoc

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3708]
In both cases the problem is something contained in `analysis_options.yaml` in the package.
The analyzer instance used by dartdoc probably shouldn't be allowed to read the `analysis_options.yaml` from the package. What is it good for?

This can be done without deleting the file, we can simply overlay it, as we did in the `pub` command line tool:
https://github.com/dart-lang/pub/blob/b239ada4b0f80cf4581be10251fa94b02689ef86/lib/src/dart.dart#L93-L101

From logs:
```
pub.dartdoc.runner/imgur/1.1.1: Error while running dartdoc for imgur 1.1.1.
exitCode: 255
stdout: 
stderr: Unhandled exception:
Error on line 13, column 13: Undefined alias.
   ╷
13 │   exclude: [*.g.dart]
   │             ^^^^^^^^
   ╵
#0      Loader._loadAlias (package:yaml/src/loader.dart:108:5)
#1      Loader._loadNode (package:yaml/src/loader.dart:80:16)
#2      Loader._loadSequence (package:yaml/src/loader.dart:140:20)
#3      Loader._loadNode (package:yaml/src/loader.dart:84:16)
#4      Loader._loadMapping (package:yaml/src/loader.dart:163:19)
#5      Loader._loadNode (package:yaml/src/loader.dart:86:16)
#6      Loader._loadMapping (package:yaml/src/loader.dart:163:19)
#7      Loader._loadNode (package:yaml/src/loader.dart:86:16)
#8      Loader._loadDocument (package:yaml/src/loader.dart:62:20)
#9      Loader.load (package:yaml/src/loader.dart:54:20)
#10     loadYamlDocument (package:yaml/yaml.dart:51:25)
#11     loadYamlNode (package:yaml/yaml.dart:42:5)
#12     loadYaml (package:yaml/yaml.dart:34:5)
#13     new _FilePackageMeta (package:dartdoc/src/package_meta.dart:295:26)
#14     PubPackageMeta.fromDir (package:dartdoc/src/package_meta.dart:223:27)
#15     createDartdocOptions.<anonymous closure> (package:dartdoc/src/dartdoc_options.dart:1596:19)
#16     DartdocSyntheticOption._valueAtFromSynthetic (package:dartdoc/src/dartdoc_options.dart:798:44)
#17     DartdocSyntheticOption.valueAt (package:dartdoc/src/dartdoc_options.dart:794:31)
#18     createGeneratorOptions.<anonymous closure> (package:dartdoc/src/generator/generator.dart:78:51)
#19     DartdocSyntheticOption._valueAtFromSynthetic (package:dartdoc/src/dartdoc_options.dart:798:44)
#20     DartdocSyntheticOption.valueAt (package:dartdoc/src/dartdoc_options.dart:794:31)
#21     GeneratorContext.addSdkFooter (package:dartdoc/src/generator/generator.dart:41:54)
#22     Templates.fromContext (package:dartdoc/src/generator/templates.dart:199:17)
#23     initHtmlGenerator (package:dartdoc/src/generator/html_generator.dart:22:35)
#24     Dartdoc.fromContext (package:dartdoc/dartdoc.dart:148:27)
#25     main (file:///project/pkg/pub_dartdoc/bin/pub_dartdoc.dart:25:33)
<asynchronous suspension>
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

From logs:
```
pub.dartdoc.runner/azblob/1.0.3: Error while running dartdoc for azblob 1.0.3.
exitCode: 255
stdout: 
stderr: Unhandled exception:
Error on line 5, column 1: Duplicate mapping key.
  ╷
5 │ include: package:effective_dart/analysis_options.yaml
  │ ^^^^^^^
  ╵
#0      Loader._loadMapping (package:yaml/src/loader.dart:165:9)
#1      Loader._loadNode (package:yaml/src/loader.dart:86:16)
#2      Loader._loadDocument (package:yaml/src/loader.dart:62:20)
#3      Loader.load (package:yaml/src/loader.dart:54:20)
#4      loadYamlDocument (package:yaml/yaml.dart:51:25)
#5      loadYamlNode (package:yaml/yaml.dart:42:5)
#6      loadYaml (package:yaml/yaml.dart:34:5)
#7      new _FilePackageMeta (package:dartdoc/src/package_meta.dart:295:26)
#8      PubPackageMeta.fromDir (package:dartdoc/src/package_meta.dart:223:27)
#9      createDartdocOptions.<anonymous closure> (package:dartdoc/src/dartdoc_options.dart:1596:19)
#10     DartdocSyntheticOption._valueAtFromSynthetic (package:dartdoc/src/dartdoc_options.dart:798:44)
#11     DartdocSyntheticOption.valueAt (package:dartdoc/src/dartdoc_options.dart:794:31)
#12     createGeneratorOptions.<anonymous closure> (package:dartdoc/src/generator/generator.dart:78:51)
#13     DartdocSyntheticOption._valueAtFromSynthetic (package:dartdoc/src/dartdoc_options.dart:798:44)
#14     DartdocSyntheticOption.valueAt (package:dartdoc/src/dartdoc_options.dart:794:31)
#15     GeneratorContext.addSdkFooter (package:dartdoc/src/generator/generator.dart:41:54)
#16     Templates.fromContext (package:dartdoc/src/generator/templates.dart:199:17)
#17     initHtmlGenerator (package:dartdoc/src/generator/html_generator.dart:22:35)
#18     Dartdoc.fromContext (package:dartdoc/dartdoc.dart:148:27)
#19     main (file:///project/pkg/pub_dartdoc/bin/pub_dartdoc.dart:25:33)
<asynchronous suspension>
#20     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by isoos** [comment]
This has been fixed in dartdoc 0.32.4 or earlier.
