### ISSUE TITLE
workerSetup() fails when restarting isolates

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3763]
From logs on staging... The `stdout: Flutter setup aborted: /flutter already exists, assuming proper setup.` line repeats a few times. Not entirely sure what is going on yet.

```
> Package: analyzer
>   Path constraint for package analysis_tool: ../analysis_tool
...
> Killed
> stdout: Flutter setup aborted: /flutter already exists, assuming proper setup.
pub.analyzer: About to start frontend isolate #1..
pub.analyzer: Frontend isolate #1 started
Unhandled exception:
Exception: Failed to checkout flutter (exited with 1)
stdout: Flutter setup aborted: /flutter already exists, assuming proper setup.
stderr: 
#0      initFlutterSdk (package:pub_dev/service/entrypoint/_gae_setup.dart:30:9)
<asynchronous suspension>
#1      AnalyzerCommand.run.workerSetup (package:pub_dev/service/entrypoint/analyzer.dart:48:13)
#2      startIsolates.<anonymous closure> (package:pub_dev/service/entrypoint/_isolate.dart:201:28)
<asynchronous suspension>
#3      startIsolates.<anonymous closure> (package:pub_dev/service/entrypoint/_isolate.dart)
#4      _withRedisCache (package:pub_dev/shared/redis_cache.dart:219:20)
<asynchronous suspension>
#5      withCache (package:pub_dev/shared/redis_cache.dart:197:18)
#6      withPubServices.<anonymous closure> (package:pub_dev/service/services.dart:115:18)
<asynchronous suspension>
#7      withPubServices.<anonymous closure> (package:pub_dev/service/services.dart)
#8      _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:207:19)
#9      _rootRun (dart:async/zone.dart:1184:13)
#10     _CustomZone.run (dart:async/zone.dart:1077:19)
#11     _runZoned (dart:async/zone.dart:1619:10)
#12     runZoned (dart:async/zone.dart:1539:10)
#13     _ServiceScope._fork (package:gcloud/service_scope.dart:206:12)
#14     fork (package:gcloud/service_scope.dart:102:30)
#15     withPubServices (package:pub_dev/service/services.dart:55:10)
#16     withServices.<anonymous closure>.<anonymous closure> (package:pub_dev/service/services.dart:47:20)
#17     withStorageRetry.<anonymous closure> (package:pub_dev/shared/storage_retry.dart:46:13)
#18     _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:207:19)
#19     _rootRun (dart:async/zone.dart:1184:13)
#20     _CustomZone.run (dart:async/zone.dart:1077:19)
#21     _runZoned (dart:async/zone.dart:1619:10)
#22     runZoned (dart:async/zone.dart:1539:10)
#23     _ServiceScope._fork (package:gcloud/service_scope.dart:206:12)
#24     fork (package:gcloud/service_scope.dart:102:30)
#25     withStorageRetry (package:pub_dev/shared/storage_retry.dart:24:16)
#26     withServices.<anonymous closure> (package:pub_dev/service/services.dart:46:18)
#27     withAppEngineServices.<anonymous closure> (package:appengine/src/appengine_internal.dart:38:51)
#28     _withAppEngineServicesInternal.<anonymous closure> (package:appengine/src/appengine_internal.dart:111:20)
<asynchronous suspension>
#29     _withAppEngineServicesInternal.<anonymous closure> (package:appengine/src/appengine_internal.dart)
#30     _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:207:19)
#31     _rootRun (dart:async/zone.dart:1184:13)
#32     _CustomZone.run (dart:async/zone.dart:1077:19)
#33     _runZoned (dart:async/zone.dart:1619:10)
#34     runZoned (dart:async/zone.dart:1539:10)
#35     _ServiceScope._fork (package:gcloud/service_scope.dart:206:12)
#36     fork (package:gcloud/service_scope.dart:102:30)
#37     _withAppEngineServicesInternal (package:appengine/src/appengine_internal.dart:102:10)
#38     withAppEngineServices (package:appengine/src/appengine_internal.dart:38:5)
#39     withAppEngineServices (package:appengine/appengine.dart:150:10)
#40     withServices (package:pub_dev/service/services.dart:45:10)
#41     startIsolates (package:pub_dev/service/entrypoint/_isolate.dart:193:11)
#42     AnalyzerCommand.run (package:pub_dev/service/entrypoint/analyzer.dart:51:11)
#43     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#44     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#45     new Future.sync (dart:async/future.dart:224:31)
#46     CommandRunner.run (package:args/command_runner.dart:112:14)
#47     main (file:///project/app/bin/server.dart:18:16)
#48     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#49     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
pub.analyzer: Setting up flutter checkout. This may take some time
pana: Running `/project/app/script/setup-flutter.sh 1.17.4`..
Triggering app shutdown handlers.  aef-analyzer-jonasfj2-50h2
Sending SIGTERM to app.  aef-analyzer-jonasfj2-50h2
9f7d5232ef086795ec3c8e1e99c24708db896c5acb5f4c3ad813ca07fce113ed  aef-analyzer-jonasfj2-50h2
Sending SIGKILL to app.  aef-analyzer-jonasfj2-50h2
Waiting for termination, 1 seconds remaining.  aef-analyzer-jonasfj2-50h2
Waiting for termination, 2 seconds remaining.  aef-analyzer-jonasfj2-50h2
Waiting for termination, 3 seconds remaining.  aef-analyzer-jonasfj2-50h2
Waiting for termination, 4 seconds remaining.  aef-analyzer-jonasfj2-50h2
Waiting for termination, 5 seconds remaining.  aef-analyzer-jonasfj2-50h2
Waiting for termination, 6 seconds remaining.  aef-analyzer-jonasfj2-50h2
Waiting for termination, 7 seconds remaining.  aef-analyzer-jonasfj2-50h2
Waiting for termination, 8 seconds remaining.  aef-analyzer-jonasfj2-50h2
Waiting for termination, 9 seconds remaining.  aef-analyzer-jonasfj2-50h2
Waiting for termination, 10 seconds remaining.  aef-analyzer-jonasfj2-50h2
Waiting for termination, 11 seconds remaining.  aef-analyzer-jonasfj2-50h2
Waiting for termination, 12 seconds remaining.  aef-analyzer-jonasfj2-50h2
Error response from daemon: Cannot kill container: 9f7d5232ef086795ec3c8e1e99c24708db896c5acb5f4c3ad813ca07fce113ed: Container 9f7d5232ef086795ec3c8e1e99c24708db896c5acb5f4c3ad813ca07fce113ed is not running  aef-analyzer-jonasfj2-50h2
App shutdown handlers done.  aef-analyzer-jonasfj2-50h2
```

**Comment by jonasfj** [comment]
This is not the underlying problem.

There is a problem here that restarts don't work because of `workerSetup()`.

This is a problem because when our process dies, App Engine restarts the process within the existing container.
If this continues to fail, AppEngine will restart the entire VM.

We recover when the VM is restarted, but not when the process inside the container is restarted.

**Comment by jonasfj** [comment]
@isoos, is there any reason we don't just move this into the docker image? That way instances don't have to spend time downloading and installing flutter when they are starting up?

I know that this means images will be bigger, and that `default` and `search` don't really need flutter.. but is it likely to cause much pain?

**Comment by isoos** [comment]
> images will be bigger, and that default and search don't really need flutter

yes, these were the reasons, and the pain of longer deploy times. otherwise we can move it to docker image.

**Comment by isoos** [comment]
This has been moved to the Dockerfile.
