### ISSUE TITLE
type '(HttpException) => Null' is not a subtype of type '(dynamic) => dynamic'

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3802]
Maybe this is not an bug... it's not entirely clear what is up. The stacktrace isn't any longer than this.

From logs: 
```
 "pub.analyzer.pana: Failed (v0.13.14) - linksdk/3.3.1

Error:
    type '(HttpException) => Null' is not a subtype of type '(dynamic) => dynamic'

Stack:
    #0      _invokeErrorHandler (dart:async/async_error.dart:18:23)
    #1      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:288:9)
    #2      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:170:13)
    #3      StackZoneSpecification._registerBinaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:141:26)
    #4      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #5      StackZoneSpecification._registerBinaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:141:14)
    #6      _rootRunBinary (dart:async/zone.dart:1204:38)
    #7      _CustomZone.runBinary (dart:async/zone.dart:1093:19)
    #8      _CustomZone.runBinaryGuarded (dart:async/zone.dart:995:7)
    #9      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358:15)
    #10     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376:16)
    #11     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:275:7)
    #12     _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:139:11)
    #13     _addErrorWithReplacement (dart:async/stream_pipe.dart:190:8)
    #14     _HandleErrorStream._handleError (dart:async/stream_pipe.dart:293:11)
    #15     _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:170:13)
    #16     StackZoneSpecification._registerBinaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:141:26)
    #17     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #18     StackZoneSpecification._registerBinaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:141:14)
    #19     _rootRunBinary (dart:async/zone.dart:1204:38)
    #20     _CustomZone.runBinary (dart:async/zone.dart:1093:19)
    #21     _CustomZone.runBinaryGuarded (dart:async/zone.dart:995:7)
    #22     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358:15)
    #23     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376:16)
    #24     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:275:7)
    #25     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:783:19)
    #26     _StreamController._addError (dart:async/stream_controller.dart:663:7)
    #27     _StreamController.addError (dart:async/stream_controller.dart:615:5)
    #28     _HttpParser._reportBodyError (dart:_http/http_parser.dart:1150:21)
    #29     _HttpParser._onDone (dart:_http/http_parser.dart:862:9)
    #30     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #31     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #32     _rootRun (dart:async/zone.dart:1180:38)
    #33     _CustomZone.run (dart:async/zone.dart:1077:19)
    #34     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
    #35     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
    #36     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:15)
    #37     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:286:7)
    #38     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:787:19)
    #39     _StreamController._closeUnchecked (dart:async/stream_controller.dart:644:7)
    #40     _StreamController.close (dart:async/stream_controller.dart:637:5)
    #41     _Socket._onData (dart:io-patch/socket_patch.dart:1989:21)
    #42     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
    #43     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #44     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
    #45     _rootRunUnary (dart:async/zone.dart:1192:38)
    #46     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
    #47     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
    #48     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
    #49     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
    #50     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
    #51     _StreamController._add (dart:async/stream_controller.dart:655:7)
    #52     _StreamController.add (dart:async/stream_controller.dart:597:5)
    #53     _RawSecureSocket._closeHandler (dart:io/secure_socket.dart:811:21)
    #54     _RawSecureSocket._eventDispatcher (dart:io/secure_socket.dart:768:9)
    #55     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
    #56     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #57     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
    #58     _rootRunUnary (dart:async/zone.dart:1196:13)
    #59     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
    #60     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
    #61     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
    #62     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
    #63     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
    #64     _StreamController._add (dart:async/stream_controller.dart:655:7)
    #65     _StreamController.add (dart:async/stream_controller.dart:597:5)
    #66     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1534:35)
    #67     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1012:18)
    #68     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
    #69     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
    #70     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
    #71     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

Followed by:
```
pub.analyzer.pana: Retrying linksdk 3.3.1...
pub.scorecard.backend: Creating new report: linksdk 3.3.1 pana. 
pub.scorecard.backend: Creating new ScoreCard linksdk 3.3.1. 
pub.job: analyzer job completed: linksdk 3.3.1 
pub.job.backend: Updating linksdk 3.3.1 with JobStatus.success 
```

**Comment by isoos** [comment]
I think this has been an issue in `package:http` and it has been fixed in https://github.com/dart-lang/http/pull/429 (`http 0.12.2`)
