### ISSUE TITLE
/api/packages --> 500

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3990]
```
api_builder: Unhandled error in API handler (incidentId: 32a85925-5530-491a-872b-143e8bbcbbc9)

Error:
    Could not successfully look up all keys due to resource constraints.

Stack:
    #0      GrpcDatastoreImpl.lookup (package:appengine/src/grpc_api_impl/datastore_impl.dart:151:9)
    <asynchronous suspension>
    #1      _lookupHelper (package:gcloud/src/db/db.dart:426:8)
    #2      DatastoreDB.lookup (package:gcloud/src/db/db.dart:338:12)
    #3      PackageBackend.lookupLatestVersions (package:pub_dev/package/backend.dart:167:22)
    #4      apiPackagesHandler.<anonymous closure> (package:pub_dev/frontend/handlers/custom_api.dart:109:30)
    <asynchronous suspension>
    #5      apiPackagesHandler.<anonymous closure> (package:pub_dev/frontend/handlers/custom_api.dart)
    #6      _Entry.get (package:neat_cache/neat_cache.dart:175:35)
    <asynchronous suspension>
    #7      apiPackagesHandler (package:pub_dev/frontend/handlers/custom_api.dart:99:54)
    <asynchronous suspension>
    #8      PubApi.listPackages (package:pub_dev/frontend/handlers/pubapi.dart:307:14)
    #9      _$PubApiRouter.<anonymous closure> (package:pub_dev/frontend/handlers/pubapi.g.dart:414:38)
    #10     _Closure.call (dart:core-patch/function.dart)
    #11     RouterEntry.invoke.<anonymous closure> (package:shelf_router/src/router_entry.dart:104:30)
```

**Comment by isoos** [comment]
This has been fixed.
