### ISSUE TITLE
cannot publish flutter package with symlink file on Windows

### ISSUE THREAD

**Issue by boyan01** [dart-lang/pub-dev#3997]
copy from https://github.com/flutter/flutter/issues/65289

The problem occurs in this [library](https://github.com/boyan01/system_clock). 

Because some code logic can be shared on multiple platforms, symlink is used to link the cpp source files that need to be shared. 

But on Windows, when I publish to pub I got this error :
```error
Package archive is empty (size = 0).
```

 Do it is impossible to use `flutter pub publish` to publish this library to pub? Is this a flutter problem or a pub problem?

<details>
<summary>the log of flutter pub publish</summary>

```log
PS C:\Users\boyan\workspace\system_clock> flutter pub publish
Publishing system_clock 0.4.1 to https://pub.dartlang.org:
|-- .gitignore
|-- .metadata
|-- .vscode
|   '-- settings.json
|-- CHANGELOG.md
|-- LICENSE
|-- README.md
|-- android
|   |-- .gitignore
|   |-- build.gradle
|   |-- gradle
|   |   '-- wrapper
|   |       '-- gradle-wrapper.properties
|   |-- gradle.properties
|   |-- settings.gradle
|   '-- src
|       '-- main
|           |-- AndroidManifest.xml
|           |-- cpp
|           |   '-- CMakeLists.txt
|           '-- java
|               '-- tech
|                   '-- soit
|                       '-- flutter
|                           '-- system_clock
|                               '-- SystemClockPlugin.java
|-- cpp
|   |-- include
|   |   '-- system_clock.h
|   '-- system_clock.cpp
|-- example
|   |-- .gitignore
|   |-- .metadata
|   |-- README.md
|   |-- android
|   |   |-- .gitignore
|   |   |-- app
|   |   |   |-- build.gradle
|   |   |   '-- src
|   |   |       |-- debug
|   |   |       |   '-- AndroidManifest.xml
|   |   |       |-- main
|   |   |       |   |-- AndroidManifest.xml
|   |   |       |   |-- kotlin
|   |   |       |   |   '-- tech
|   |   |       |   |       '-- soit
|   |   |       |   |           '-- flutter
|   |   |       |   |               '-- system_clock_example
|   |   |       |   |                   '-- MainActivity.kt
|   |   |       |   '-- res
|   |   |       |       |-- drawable
|   |   |       |       |   '-- launch_background.xml
|   |   |       |       |-- mipmap-hdpi
|   |   |       |       |   '-- ic_launcher.png
|   |   |       |       |-- mipmap-mdpi
|   |   |       |       |   '-- ic_launcher.png
|   |   |       |       |-- mipmap-xhdpi
|   |   |       |       |   '-- ic_launcher.png
|   |   |       |       |-- mipmap-xxhdpi
|   |   |       |       |   '-- ic_launcher.png
|   |   |       |       |-- mipmap-xxxhdpi
|   |   |       |       |   '-- ic_launcher.png
|   |   |       |       '-- values
|   |   |       |           '-- styles.xml
|   |   |       '-- profile
|   |   |           '-- AndroidManifest.xml
|   |   |-- build.gradle
|   |   |-- gradle
|   |   |   '-- wrapper
|   |   |       '-- gradle-wrapper.properties
|   |   |-- gradle.properties
|   |   '-- settings.gradle
|   |-- ios
|   |   |-- .gitignore
|   |   |-- Flutter
|   |   |   |-- AppFrameworkInfo.plist
|   |   |   |-- Debug.xcconfig
|   |   |   '-- Release.xcconfig
|   |   |-- Podfile
|   |   |-- Podfile.lock
|   |   |-- Runner
|   |   |   |-- AppDelegate.swift
|   |   |   |-- Assets.xcassets
|   |   |   |   |-- AppIcon.appiconset
|   |   |   |   |   |-- Contents.json
|   |   |   |   |   |-- Icon-App-1024x1024@1x.png
|   |   |   |   |   |-- Icon-App-20x20@1x.png
|   |   |   |   |   | (10 more...)
|   |   |   |   |   |-- Icon-App-76x76@1x.png
|   |   |   |   |   |-- Icon-App-76x76@2x.png
|   |   |   |   |   '-- Icon-App-83.5x83.5@2x.png
|   |   |   |   '-- LaunchImage.imageset
|   |   |   |       |-- Contents.json
|   |   |   |       |-- LaunchImage.png
|   |   |   |       |-- LaunchImage@2x.png
|   |   |   |       |-- LaunchImage@3x.png
|   |   |   |       '-- README.md
|   |   |   |-- Base.lproj
|   |   |   |   |-- LaunchScreen.storyboard
|   |   |   |   '-- Main.storyboard
|   |   |   |-- Info.plist
|   |   |   '-- Runner-Bridging-Header.h
|   |   |-- Runner.xcodeproj
|   |   |   |-- project.pbxproj
|   |   |   |-- project.xcworkspace
|   |   |   |   |-- contents.xcworkspacedata
|   |   |   |   '-- xcshareddata
|   |   |   |       |-- IDEWorkspaceChecks.plist
|   |   |   |       '-- WorkspaceSettings.xcsettings
|   |   |   '-- xcshareddata
|   |   |       '-- xcschemes
|   |   |           '-- Runner.xcscheme
|   |   '-- Runner.xcworkspace
|   |       |-- contents.xcworkspacedata
|   |       '-- xcshareddata
|   |           |-- IDEWorkspaceChecks.plist
|   |           '-- WorkspaceSettings.xcsettings
|   |-- lib
|   |   '-- main.dart
|   |-- macos
|   |   |-- .gitignore
|   |   |-- Flutter
|   |   |   |-- Flutter-Debug.xcconfig
|   |   |   |-- Flutter-Release.xcconfig
|   |   |   '-- GeneratedPluginRegistrant.swift
|   |   |-- Podfile
|   |   |-- Podfile.lock
|   |   |-- Runner
|   |   |   |-- AppDelegate.swift
|   |   |   |-- Assets.xcassets
|   |   |   |   '-- AppIcon.appiconset
|   |   |   |       |-- Contents.json
|   |   |   |       |-- app_icon_1024.png
|   |   |   |       |-- app_icon_128.png
|   |   |   |       |-- app_icon_16.png
|   |   |   |       |-- app_icon_256.png
|   |   |   |       |-- app_icon_32.png
|   |   |   |       |-- app_icon_512.png
|   |   |   |       '-- app_icon_64.png
|   |   |   |-- Base.lproj
|   |   |   |   '-- MainMenu.xib
|   |   |   |-- Configs
|   |   |   |   |-- AppInfo.xcconfig
|   |   |   |   |-- Debug.xcconfig
|   |   |   |   |-- Release.xcconfig
|   |   |   |   '-- Warnings.xcconfig
|   |   |   |-- DebugProfile.entitlements
|   |   |   |-- Info.plist
|   |   |   |-- MainFlutterWindow.swift
|   |   |   '-- Release.entitlements
|   |   |-- Runner.xcodeproj
|   |   |   |-- project.pbxproj
|   |   |   |-- project.xcworkspace
|   |   |   |   '-- xcshareddata
|   |   |   |       '-- IDEWorkspaceChecks.plist
|   |   |   '-- xcshareddata
|   |   |       '-- xcschemes
|   |   |           '-- Runner.xcscheme
|   |   '-- Runner.xcworkspace
|   |       |-- contents.xcworkspacedata
|   |       '-- xcshareddata
|   |           '-- IDEWorkspaceChecks.plist
|   |-- pubspec.yaml
|   |-- test
|   |   '-- widget_test.dart
|   '-- windows
|       |-- .gitignore
|       |-- CMakeLists.txt
|       |-- flutter
|       |   |-- .template_version
|       |   |-- CMakeLists.txt
|       |   |-- generated_plugin_registrant.cc
|       |   |-- generated_plugin_registrant.h
|       |   '-- generated_plugins.cmake
|       '-- runner
|           |-- CMakeLists.txt
|           |-- Runner.rc
|           |-- flutter_window.cpp
|           | (10 more...)
|           |-- win32_window.h
|           |-- window_configuration.cpp
|           '-- window_configuration.h
|-- ios
|   |-- .gitignore
|   |-- Assets
|   |   '-- .gitkeep
|   |-- Classes
|   |   |-- SystemClockPlugin.h
|   |   |-- SystemClockPlugin.m
|   |   |-- include
|   |   |   '-- system_clock.mm
|   |   '-- system_clock.cpp
|   '-- system_clock.podspec
|-- lib
|   '-- system_clock.dart
|-- macos
|   |-- Classes
|   |   |-- SystemClockPlugin.swift
|   |   |-- include
|   |   |   '-- system_clock.mm
|   |   '-- system_clock.cpp
|   '-- system_clock.podspec
|-- pubspec.yaml
|-- system_clock.iml
|-- test
|   '-- system_clock_test.dart
'-- windows
    |-- .gitignore
    |-- CMakeLists.txt
    |-- include
    |   |-- system_clock
    |   |   '-- system_clock_plugin.h
    |   '-- system_clock.h
    |-- system_clock.cpp
    '-- system_clock_plugin.cpp
Package validation found the following potential issues:
* Your pubspec.yaml includes an "author" section which is no longer used and may be removed.
* .\CHANGELOG.md doesn't mention current version (0.4.1).
  Consider updating it with notes on this version prior to publication.

Publishing is forever; packages cannot be unpublished.
Policy details are available at https://pub.dev/policy


Package has 2 warnings.. Do you want to publish system_clock 0.4.1 (y/N)? y
Uploading...
Package archive is empty (size = 0).
pub finished with exit code 1
```

</details>

<details>
<summary>flutter doctor -v</summary>

```log
[✓] Flutter (Channel master, 1.22.0-10.0.pre.87, on Microsoft Windows [Version 10.0.19041.450], locale zh-CN)
    • Flutter version 1.22.0-10.0.pre.87 at C:\Users\boyan\dev\flutter
    • Framework revision 4732a214a7 (17 hours ago), 2020-09-04 21:05:02 -0400
    • Engine revision ac8b9c4c52
    • Dart version 2.10.0 (build 2.10.0-86.0.dev)
    • Flutter download mirror https://storage.flutter-io.cn


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
    • Android SDK at C:\Users\boyan\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.0-rc1
    • ANDROID_HOME = C:\Users\boyan\AppData\Local\Android\Sdk
    • Java binary at: C:\Users\boyan\dev\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30413.136
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Users\boyan\dev\android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.48.2)
    • VS Code at C:\Users\boyan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (1 available)
    • Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.19041.450]

! Doctor found issues in 1 category.
```

</details>

**Comment by isoos** [comment]
The issue doesn't seem to be symlinks, as the message literally says that you were not able to create a valid package archive for uploading (the uploaded archive had zero length).

**Comment by isoos** [comment]
@boyan01: I see the package was published. Were you able to debug the issue? If not, can you run publish with `-v` (verbose logging)?

**Comment by boyan01** [comment]
The package was published by this script ([publish.dart](https://github.com/boyan01/system_clock/blob/master/tools/publish.dart)) in Linux. 

I replace the symlinks file with the "real file".


### verbose logging
```log
PS C:\Users\boyan\workspace\system_clock> flutter pub publish -v
[  +80 ms] executing: [C:\Users\boyan\dev\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +58 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 6c1a29e54c412d244256d9a23e7c1f0a76e2f0e1
[        ] executing: [C:\Users\boyan\dev\flutter/] git tag --points-at HEAD
[  +65 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] executing: [C:\Users\boyan\dev\flutter/] git describe --match *.*.* --first-parent --long --tags
[  +81 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] 1.22.0-9.0.pre-121-g6c1a29e54c
[   +6 ms] executing: [C:\Users\boyan\dev\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +34 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\Users\boyan\dev\flutter/] git ls-remote --get-url origin
[  +32 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +58 ms] executing: [C:\Users\boyan\dev\flutter/] git rev-parse --abbrev-ref HEAD
[  +32 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +46 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +8 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +16 ms] executing: C:\Users\boyan\dev\flutter\bin\cache\dart-sdk\bin\pub.bat publish
Publishing system_clock 0.4.2 to https://pub.dartlang.org:
|-- .gitignore
|-- .metadata
|-- .vscode
|   '-- settings.json
|-- CHANGELOG.md
|-- LICENSE
|-- README.md
|-- android
|   |-- .gitignore
|   |-- build.gradle
|   |-- gradle
|   |   '-- wrapper
|   |       '-- gradle-wrapper.properties
|   |-- gradle.properties
|   |-- settings.gradle
|   '-- src
|       '-- main
|           |-- AndroidManifest.xml
|           |-- cpp
|           |   '-- CMakeLists.txt
|           '-- java
|               '-- tech
|                   '-- soit
|                       '-- flutter
|                           '-- system_clock
|                               '-- SystemClockPlugin.java
|-- cpp
|   |-- include
|   |   '-- system_clock.h
|   '-- system_clock.cpp
|-- example
|   |-- .gitignore
|   |-- .metadata
|   |-- README.md
|   |-- android
|   |   |-- .gitignore
|   |   |-- app
|   |   |   |-- build.gradle
|   |   |   '-- src
|   |   |       |-- debug
|   |   |       |   '-- AndroidManifest.xml
|   |   |       |-- main
|   |   |       |   |-- AndroidManifest.xml
|   |   |       |   |-- kotlin
|   |   |       |   |   '-- tech
|   |   |       |   |       '-- soit
|   |   |       |   |           '-- flutter
|   |   |       |   |               '-- system_clock_example
|   |   |       |   |                   '-- MainActivity.kt
|   |   |       |   '-- res
|   |   |       |       |-- drawable
|   |   |       |       |   '-- launch_background.xml
|   |   |       |       |-- mipmap-hdpi
|   |   |       |       |   '-- ic_launcher.png
|   |   |       |       |-- mipmap-mdpi
|   |   |       |       |   '-- ic_launcher.png
|   |   |       |       |-- mipmap-xhdpi
|   |   |       |       |   '-- ic_launcher.png
|   |   |       |       |-- mipmap-xxhdpi
|   |   |       |       |   '-- ic_launcher.png
|   |   |       |       |-- mipmap-xxxhdpi
|   |   |       |       |   '-- ic_launcher.png
|   |   |       |       '-- values
|   |   |       |           '-- styles.xml
|   |   |       '-- profile
|   |   |           '-- AndroidManifest.xml
|   |   |-- build.gradle
|   |   |-- gradle
|   |   |   '-- wrapper
|   |   |       '-- gradle-wrapper.properties
|   |   |-- gradle.properties
|   |   '-- settings.gradle
|   |-- ios
|   |   |-- .gitignore
|   |   |-- Flutter
|   |   |   |-- AppFrameworkInfo.plist
|   |   |   |-- Debug.xcconfig
|   |   |   '-- Release.xcconfig
|   |   |-- Podfile
|   |   |-- Podfile.lock
|   |   |-- Runner
|   |   |   |-- AppDelegate.swift
|   |   |   |-- Assets.xcassets
|   |   |   |   |-- AppIcon.appiconset
|   |   |   |   |   |-- Contents.json
|   |   |   |   |   |-- Icon-App-1024x1024@1x.png
|   |   |   |   |   |-- Icon-App-20x20@1x.png
|   |   |   |   |   | (10 more...)
|   |   |   |   |   |-- Icon-App-76x76@1x.png
|   |   |   |   |   |-- Icon-App-76x76@2x.png
|   |   |   |   |   '-- Icon-App-83.5x83.5@2x.png
|   |   |   |   '-- LaunchImage.imageset
|   |   |   |       |-- Contents.json
|   |   |   |       |-- LaunchImage.png
|   |   |   |       |-- LaunchImage@2x.png
|   |   |   |       |-- LaunchImage@3x.png
|   |   |   |       '-- README.md
|   |   |   |-- Base.lproj
|   |   |   |   |-- LaunchScreen.storyboard
|   |   |   |   '-- Main.storyboard
|   |   |   |-- Info.plist
|   |   |   '-- Runner-Bridging-Header.h
|   |   |-- Runner.xcodeproj
|   |   |   |-- project.pbxproj
|   |   |   |-- project.xcworkspace
|   |   |   |   |-- contents.xcworkspacedata
|   |   |   |   '-- xcshareddata
|   |   |   |       |-- IDEWorkspaceChecks.plist
|   |   |   |       '-- WorkspaceSettings.xcsettings
|   |   |   '-- xcshareddata
|   |   |       '-- xcschemes
|   |   |           '-- Runner.xcscheme
|   |   '-- Runner.xcworkspace
|   |       |-- contents.xcworkspacedata
|   |       '-- xcshareddata
|   |           |-- IDEWorkspaceChecks.plist
|   |           '-- WorkspaceSettings.xcsettings
|   |-- lib
|   |   '-- main.dart
|   |-- macos
|   |   |-- .gitignore
|   |   |-- Flutter
|   |   |   |-- Flutter-Debug.xcconfig
|   |   |   |-- Flutter-Release.xcconfig
|   |   |   '-- GeneratedPluginRegistrant.swift
|   |   |-- Podfile
|   |   |-- Podfile.lock
|   |   |-- Runner
|   |   |   |-- AppDelegate.swift
|   |   |   |-- Assets.xcassets
|   |   |   |   '-- AppIcon.appiconset
|   |   |   |       |-- Contents.json
|   |   |   |       |-- app_icon_1024.png
|   |   |   |       |-- app_icon_128.png
|   |   |   |       |-- app_icon_16.png
|   |   |   |       |-- app_icon_256.png
|   |   |   |       |-- app_icon_32.png
|   |   |   |       |-- app_icon_512.png
|   |   |   |       '-- app_icon_64.png
|   |   |   |-- Base.lproj
|   |   |   |   '-- MainMenu.xib
|   |   |   |-- Configs
|   |   |   |   |-- AppInfo.xcconfig
|   |   |   |   |-- Debug.xcconfig
|   |   |   |   |-- Release.xcconfig
|   |   |   |   '-- Warnings.xcconfig
|   |   |   |-- DebugProfile.entitlements
|   |   |   |-- Info.plist
|   |   |   |-- MainFlutterWindow.swift
|   |   |   '-- Release.entitlements
|   |   |-- Runner.xcodeproj
|   |   |   |-- project.pbxproj
|   |   |   |-- project.xcworkspace
|   |   |   |   '-- xcshareddata
|   |   |   |       '-- IDEWorkspaceChecks.plist
|   |   |   '-- xcshareddata
|   |   |       '-- xcschemes
|   |   |           '-- Runner.xcscheme
|   |   '-- Runner.xcworkspace
|   |       |-- contents.xcworkspacedata
|   |       '-- xcshareddata
|   |           '-- IDEWorkspaceChecks.plist
|   |-- pubspec.yaml
|   |-- test
|   |   '-- widget_test.dart
|   '-- windows
|       |-- .gitignore
|       |-- CMakeLists.txt
|       |-- flutter
|       |   |-- .template_version
|       |   |-- CMakeLists.txt
|       |   |-- generated_plugin_registrant.cc
|       |   |-- generated_plugin_registrant.h
|       |   '-- generated_plugins.cmake
|       '-- runner
|           |-- CMakeLists.txt
|           |-- Runner.rc
|           |-- flutter_window.cpp
|           | (10 more...)
|           |-- win32_window.h
|           |-- window_configuration.cpp
|           '-- window_configuration.h
|-- ios
|   |-- .gitignore
|   |-- Assets
|   |   '-- .gitkeep
|   |-- Classes
|   |   |-- SystemClockPlugin.h
|   |   |-- SystemClockPlugin.m
|   |   |-- include
|   |   |   '-- system_clock.mm
|   |   '-- system_clock.cpp
|   '-- system_clock.podspec
|-- lib
|   '-- system_clock.dart
|-- macos
|   |-- Classes
|   |   |-- SystemClockPlugin.swift
|   |   |-- include
|   |   |   '-- system_clock.mm
|   |   '-- system_clock.cpp
|   '-- system_clock.podspec
|-- publish.sh
|-- pubspec.yaml
|-- system_clock.iml
|-- test
|   '-- system_clock_test.dart
|-- tools
|   |-- publish.dart
|   '-- pubspec.yaml
'-- windows
    |-- .gitignore
    |-- CMakeLists.txt
    |-- include
    |   |-- system_clock
    |   |   '-- system_clock_plugin.h
    |   '-- system_clock.h
    |-- system_clock.cpp
    '-- system_clock_plugin.cpp
Package validation found the following potential issues:
* Your pubspec.yaml includes an "author" section which is no longer used and may be removed.
* Rename the top-level "tools" directory to "tool".
  The Pub layout convention is to use singular directory names.
  Plural names won't be correctly identified by Pub and other tools.
* .\CHANGELOG.md doesn't mention current version (0.4.2).
  Consider updating it with notes on this version prior to publication.

Publishing is forever; packages cannot be unpublished.
Policy details are available at https://pub.dev/policy


Package has 3 warnings.. Do you want to publish system_clock 0.4.2 (y/N)? y
Uploading...
Package archive is empty (size = 0).
[+8192 ms] "flutter publish" took 8,240ms.
[   +4 ms] pub finished with exit code 1
[   +1 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:375:7)
           <asynchronous suspension>
           #2      PackagesPublishCommand.runCommand (package:flutter_tools/src/commands/packages.dart:230:15)
           #3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:972:18)
           #4      _rootRunUnary (dart:async/zone.dart:1198:47)
           #5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #10     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #11     _rootRun (dart:async/zone.dart:1190:13)
           #12     _CustomZone.run (dart:async/zone.dart:1093:19)
           #13     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +271 ms] ensureAnalyticsSent: 267ms
[   +6 ms] Running shutdown hooks
[   +2 ms] Shutdown hooks complete
[   +2 ms] exiting with code 1
```

**Comment by boyan01** [comment]
this problem seems belong to pub client. closing...
