### ISSUE TITLE
UserinfoResourceApi.get returns 500 in "/api/account/session"

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#4157]
I'm not sure what we should do here. Any ideas? This has thus far happened about 7 times.

* [ ] Add retries
* [ ] Handle this gracefully by letting login attempts fail.
* [ ] Log with `.shout` error and stacktrace when a log attempt fails for this reason.

```
"api_builder: Unhandled error in API handler (incidentId: xxx)

Error:
    DetailedApiRequestError(status: 500, message: Internal error encountered.)

Stack:
    #0      _validateResponse (package:_discoveryapis_commons/src/clients.dart:854:9)
    <asynchronous suspension>
    #1      ApiRequester.request (package:_discoveryapis_commons/src/clients.dart:76:22)
    <asynchronous suspension>
    #2      UserinfoResourceApi.get (package:googleapis/oauth2/v2.dart:122:32)
    #3      GoogleOauth2AuthProvider.getAccountProfile (package:pub_dev/account/google_oauth2.dart:200:40)
    <asynchronous suspension>
    #4      updateSessionHandler (package:pub_dev/frontend/handlers/account.dart:57:38)
    <asynchronous suspension>
    #5      PubApi.updateSession (package:pub_dev/frontend/handlers/pubapi.dart:257:7)
    #6      _$PubApiRouter.<anonymous closure> (package:pub_dev/frontend/handlers/pubapi.g.dart:296:38)
    <asynchronous suspension>
    #7      _$PubApiRouter.<anonymous closure> (package:pub_dev/frontend/handlers/pubapi.g.dart)
    #8      RouterEntry.invoke.<anonymous closure> (package:shelf_router/src/router_entry.dart:104:30)
    <asynchronous suspension>
    #9      RouterEntry.invoke.<anonymous closure> (package:shelf_router/src/router_entry.dart)
    #10     RouterEntry.invoke (package:shelf_router/src/router_entry.dart:108:7)
    <asynchronous suspension>
    #11     Router.handler.<anonymous closure> (package:shelf_router/src/router.dart:146:33)
```

**Comment by jonasfj** [comment]
From logs this has affected more than 3 users.. It's not the same combination of IP and user-agent for all requests that failed.

**Comment by sigurdm** [comment]
obsolete
