### ISSUE TITLE
EmailSenderFailed(500): Failed to send email, please retry later.

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#4158]
I suppose we could increase the retry limit to 3 or 5, instead of only have 2 attempts.

``` 
pub.cloud_repository: Error post-processing package upload ....

Error:
    EmailSenderFailed(500): Failed to send email, please retry later.

Stack:
    #0      _GmailSmtpRelay.sendMessage (package:pub_dev/frontend/email_sender.dart:145:7)
    <asynchronous suspension>
    #1      PackageBackend._performTarballUpload (package:pub_dev/package/backend.dart:617:33)
    <asynchronous suspension>
    #2      PackageBackend.publishUploadedBlob.<anonymous closure> (package:pub_dev/package/backend.dart:502:29)
    <asynchronous suspension>
    #3      PackageBackend.publishUploadedBlob.<anonymous closure> (package:pub_dev/package/backend.dart)
    #4      withTempDirectory.<anonymous closure> (package:pub_dev/shared/utils.dart:48:16)
    #5      StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:26)
    #6      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
    #7      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:14)
    #8      _rootRunUnary (dart:async/zone.dart:1198:47)
    #9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
    #11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
    #12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
    #13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
    #14     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
    #15     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
    #16     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:116:48)
    #17     _rootRun (dart:async/zone.dart:1190:13)
    #18     _CustomZone.run (dart:async/zone.dart:1093:19)
    #19     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
    #20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
    #21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
    #22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
    #23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
    #24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
``` 

Previously, in the same request I see two attempts to send the email failing:
```
mailer_sender: Could not send mail.

Error:
    After sending DATA, response did not start with any of: [2, 3].
    Response from server: < 421 4.3.0 Temporary System Problem.  Try again later (10). n62sm897072vke.0 - gsmtp
```

**Comment by isoos** [comment]
Alternatively, or on top of the increased retry count, we could also have a Datastore entity that stores the unsuccessful e-mails and re-tries sending them later.

**Comment by jonasfj** [comment]
Discussed this over video, concluded:
 * [ ] Increase retry count from 2 to 3.
 * [ ] Ignore email sending error, when a package is published, log warning with magic message.
 * [ ] Create custom log metric counting magic message, and alert if > 3 per day.
 * [ ] Handle exception in the invite flow, and inform user that invite was not sent, hence, try again later.
