### ISSUE TITLE
SearchClient.search, stack trace without error?

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#4189]
Not sure what happened here, seems like there was an error and a stacktrace, but the error is empty string? or renders to empty string..
```
pub.utils: HTTP GET failed on https://search-dot-dartlang-pub.appspot.com/search?q=dependency%3Aflutter_instagram_image_picker&tags=-is%3Adiscontinued&tags=-is%3Aunlisted&tags=-is%3Alegacy&tags=sdk%3Aflutter&tags=platform%3Aandroid&tags=platform%3Awindows&tags=platform%3Amacos&tags=platform%3Alinux&tags=platform%3Aweb&tags=platform%3Aios&offset=0&limit=10 (0 retry left)

Error:
    

Stack:
    #0      IOClient.send (package:http/src/io_client.dart:62:7)
    <asynchronous suspension>
    #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:91:38)
    <asynchronous suspension>
    #2      BaseClient.get (package:http/src/base_client.dart:27:7)
    #3      getUrlWithRetry (package:pub_dev/shared/utils.dart:248:45)
    <asynchronous suspension>
    #4      SearchClient.search.searchFn (package:pub_dev/search/search_client.dart:59:30)
    <asynchronous suspension>
    #5      SearchClient.search.searchFn (package:pub_dev/search/search_client.dart)
    #6      _Entry.get (package:neat_cache/neat_cache.dart:175:35)
    <asynchronous suspension>
    #7      SearchClient.search (package:pub_dev/search/search_client.dart:88:35)
    <asynchronous suspension>
    #8      SearchAdapter._searchOrFallback (package:pub_dev/package/search_adapter.dart:94:35)
    <asynchronous suspension>
    #9      SearchAdapter.search (package:pub_dev/package/search_adapter.dart:81:26)
    <asynchronous suspension>
    #10     _packagesHandlerHtmlCore (package:pub_dev/frontend/handlers/listing.dart:88:44)
    <asynchronous suspension>
    #11     flutterPackagesHandlerHtml (package:pub_dev/frontend/handlers/listing.dart:40:10)
    #12     PubSiteService.flutterPackages (package:pub_dev/frontend/handlers/routes.dart:73:7)
    #13     RouterEntry.invoke.<anonymous closure> (package:shelf_router/src/router_entry.dart:104:30)
    <asynchronous suspension>
    #14     RouterEntry.invoke.<anonymous closure> (package:shelf_router/src/router_entry.dart)
    #15     RouterEntry.invoke (package:shelf_router/src/router_entry.dart:108:7)
    <asynchronous suspension>
    #16     Router.handler.<anonymous closure> (package:shelf_router/src/router.dart:146:33)
    <asynchronous suspension>
    #17     Router.handler.<anonymous closure> (package:shelf_router/src/router.dart)
    #18     createAppHandler.<anonymous closure> (package:pub_dev/frontend/handlers.dart:60:37)
    <asynchronous suspension>
    #19     createAppHandler.<anonymous closure> (package:pub_dev/frontend/handlers.dart)
    #20     _cspHeaderWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart:116:29)
    <asynchronous suspension>
    #21     _cspHeaderWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart)
    #22     _userAuthWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart:212:25)
    <asynchronous suspension>
    #23     _userAuthWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart)
    #24     _requestContextWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart:108:25)
    <asynchronous suspension>
    #25     _requestContextWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart)
    #26     _userSessionWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart:235:38)
    <asynchronous suspension>
    #27     _userSessionWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart)
    #28     _httpsWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart:257:38)
    <asynchronous suspension>
    #29     _httpsWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart)
    #30     _sanitizeRequestWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart:191:25)
    <asynchronous suspension>
    #31     _sanitizeRequestWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart)
    #32     _logRequestWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart:140:27)
    <asynchronous suspension>
    #33     _logRequestWrapper.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart)
    #34     handleRequest (package:shelf/shelf_io.dart:101:29)
    <asynchronous suspension>
    #35     runHandler.<anonymous closure> (package:pub_dev/shared/handler_helpers.dart:53:5)
    #36     runAppEngine.<anonymous closure> (package:appengine/appengine.dart:80:12)
    #37     runAppEngine.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:58:18)
    #38     _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:207:19)
    #39     _rootRun (dart:async/zone.dart:1190:13)
    #40     _CustomZone.run (dart:async/zone.dart:1093:19)
    #41     _runZoned (dart:async/zone.dart:1630:10)
    #42     runZonedGuarded (dart:async/zone.dart:1618:12)
    #43     runZoned (dart:async/zone.dart:1547:12)
    #44     _ServiceScope._fork (package:gcloud/service_scope.dart:206:12)
    #45     fork (package:gcloud/service_scope.dart:102:30)
    #46     runAppEngine.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:56:9)
    #47     AppEngineHttpServer.run.<anonymous closure>.<anonymous closure> (package:appengine/src/server/server.dart:83:16)
    #48     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:26)
    #49     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
    #50     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:14)
    #51     _rootRunUnary (dart:async/zone.dart:1198:47)
    #52     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #53     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
    #54     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
    #55     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
    #56     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
    #57     _StreamController._add (dart:async/stream_controller.dart:682:7)
    #58     _StreamController.add (dart:async/stream_controller.dart:624:5)
    #59     _HttpServer._handleRequest (dart:_http/http_impl.dart:2977:19)
    #60     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2732:19)
    #61     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:26)
    #62     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
    #63     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:14)
    #64     _rootRunUnary (dart:async/zone.dart:1198:47)
    #65     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #66     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
    #67     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
    #68     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
    #69     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
    #70     _StreamController._add (dart:async/stream_controller.dart:682:7)
    #71     _StreamController.add (dart:async/stream_controller.dart:624:5)
    #72     _HttpParser._headersEnd (dart:_http/http_parser.dart:394:19)
    #73     _HttpParser._doParse (dart:_http/http_parser.dart:740:15)
    #74     _HttpParser._parse (dart:_http/http_parser.dart:324:7)
    #75     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:26)
    #76     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
    #77     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:14)
    #78     _rootRunUnary (dart:async/zone.dart:1198:47)
    #79     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #80     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
    #81     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
    #82     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
    #83     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
    #84     _StreamController._add (dart:async/stream_controller.dart:682:7)
    #85     _StreamController.add (dart:async/stream_controller.dart:624:5)
    #86     _Socket._onData (dart:io-patch/socket_patch.dart:2044:41)
    #87     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:26)
    #88     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
    #89     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:14)
    #90     _rootRunUnary (dart:async/zone.dart:1206:13)
    #91     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #92     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
    #93     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
    #94     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
    #95     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
    #96     _StreamController._add (dart:async/stream_controller.dart:682:7)
    #97     _StreamController.add (dart:async/stream_controller.dart:624:5)
    #98     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1580:33)
    #99     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1076:14)
    #100    _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
    #101    _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
    #102    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
    #103    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by jonasfj** [comment]
Only two occurences so far.

**Comment by isoos** [comment]
This is coming from the non-`package:retry`-based `getUrlWithRetry`:
https://github.com/dart-lang/pub-dev/blob/master/app/lib/shared/utils.dart#L238
