### ISSUE TITLE
dartdoc -- NoSuchMethodError: The getter 'importedExportedLibraries' was called on null.

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#4238]
We need to reproduce and file a bug with dartdoc, if it's not `pub-dev` specific.

```
pub.dartdoc.runner/flutter_instagram_stories/0.1.5+4: Error while running dartdoc for flutter_instagram_stories 0.1.5+4.
exitCode: 255
stdout: Documenting flutter_instagram_stories...
Initialized dartdoc with 1072 libraries in 150.3 seconds
Generating docs for library flutter_instagram_stories from package:flutter_instagram_stories/flutter_instagram_stories.dart...
stderr: Unhandled exception:
NoSuchMethodError: The getter 'importedExportedLibraries' was called on null.
Receiver: null
Tried calling: importedExportedLibraries
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Library.importedExportedLibraries (package:dartdoc/src/model/library.dart:272:47)
#2      Library.packageImportedExportedLibraries.<anonymous closure> (package:dartdoc/src/model/library.dart:253:52)
#3      Iterable.forEach (dart:core/iterable.dart:283:30)
#4      Library.packageImportedExportedLibraries (package:dartdoc/src/model/library.dart:252:12)
#5      _MarkdownCommentReference._reducePreferLibrariesInLocalImportExportGraph.<anonymous closure> (package:dartdoc/src/markdown_processor.dart:531:24)
#6      SetMixin.any (dart:collection/set.dart:190:15)
#7      _MarkdownCommentReference._reducePreferLibrariesInLocalImportExportGraph (package:dartdoc/src/markdown_processor.dart:530:17)
#8      _MarkdownCommentReference.computeReferredElement (package:dartdoc/src/markdown_processor.dart:471:21)
#9      _getMatchingLinkElement (package:dartdoc/src/markdown_processor.dart:240:12)
#10     _makeLinkNode (package:dartdoc/src/markdown_processor.dart:855:16)
#11     new MarkdownDocument.withElementLinkResolver.linkResolver (package:dartdoc/src/markdown_processor.dart:950:14)
#12     LinkSyntax._resolveReferenceLink (package:markdown/src/inline_parser.dart:807:26)
#13     LinkSyntax._tryAddReferenceLink (package:markdown/src/inline_parser.dart:829:9)
#14     LinkSyntax.onMatchEnd (package:markdown/src/inline_parser.dart:777:12)
#15     TagState.close (package:markdown/src/inline_parser.dart:1311:16)
#16     TagState.tryMatch (package:markdown/src/inline_parser.dart:1250:7)
#17     InlineParser.parse.<anonymous closure> (package:markdown/src/inline_parser.dart:105:57)
#18     ListIterable.any (dart:_internal/iterable.dart:89:15)
#19     InlineParser.parse (package:markdown/src/inline_parser.dart:105:12)
#20     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_processor.dart:997:67)
#21     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_processor.dart:1002:9)
#22     MarkdownDocument.parseMarkdownText (package:dartdoc/src/markdown_processor.dart:987:5)
#23     Documentation._parseDocumentation (package:dartdoc/src/model/documentation.dart:71:21)
#24     Documentation._renderDocumentation (package:dartdoc/src/model/documentation.dart:48:23)
#25     Documentation.asOneLiner (package:dartdoc/src/model/documentation.dart:40:7)
#26     ModelElement.oneLineDoc (package:dartdoc/src/model/model_element.dart:1029:43)
#27     _InstanceMirror._invokeGetter (dart:mirrors-patch/mirrors_impl.dart:339:76)
#28     _InstanceMirror.getField (dart:mirrors-patch/mirrors_impl.dart:306:20)
#29     Renderer._getNamedProperty (package:mustache/src/renderer.dart:245:29)
#30     Renderer.resolveValue (package:mustache/src/renderer.dart:212:16)
#31     Renderer.visitVariable (package:mustache/src/renderer.dart:90:17)
#32     VariableNode.accept (package:mustache/src/node.dart:45:43)
#33     Renderer.render.<anonymous closure> (package:mustache/src/renderer.dart:64:53)
#34     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#35     Renderer.render (package:mustache/src/renderer.dart:64:36)
#36     Renderer.visitPartial (package:mustache/src/renderer.dart:195:16)
#37     PartialNode.accept (package:mustache/src/node.dart:81:43)
#38     SectionNode.visitChildren.<anonymous closure> (package:mustache/src/node.dart:66:37)
#39     List.forEach (dart:core-patch/growable_array.dart:313:8)
#40     SectionNode.visitChildren (package:mustache/src/node.dart:66:14)
#41     Renderer._renderWithValue (package:mustache/src/renderer.dart:184:10)
#42     Renderer._renderSection.<anonymous closure> (package:mustache/src/renderer.dart:126:28)
#43     Iterable.forEach (dart:core/iterable.dart:283:30)
#44     Renderer._renderSection (package:mustache/src/renderer.dart:126:13)
#45     Renderer.visitSection (package:mustache/src/renderer.dart:115:7)
#46     SectionNode.accept (package:mustache/src/node.dart:63:43)
#47     SectionNode.visitChildren.<anonymous closure> (package:mustache/src/node.dart:66:37)
#48     List.forEach (dart:core-patch/growable_array.dart:313:8)
#49     SectionNode.visitChildren (package:mustache/src/node.dart:66:14)
#50     Renderer._renderWithValue (package:mustache/src/renderer.dart:184:10)
#51     Renderer._renderSection (package:mustache/src/renderer.dart:130:7)
#52     Renderer.visitSection (package:mustache/src/renderer.dart:115:7)
#53     SectionNode.accept (package:mustache/src/node.dart:63:43)
#54     Renderer.render.<anonymous closure> (package:mustache/src/renderer.dart:58:30)
#55     List.forEach (dart:core-patch/growable_array.dart:313:8)
#56     Renderer.render (package:mustache/src/renderer.dart:58:13)
#57     Template.render (package:mustache/src/template.dart:40:14)
#58     Template.renderString (package:mustache/src/template.dart:33:5)
#59     DartdocGeneratorBackend.render (package:dartdoc/src/generator/dartdoc_generator_backend.dart:59:28)
#60     DartdocGeneratorBackend.generateLibrary (package:dartdoc/src/generator/dartdoc_generator_backend.dart:105:5)
#61     GeneratorFrontEnd._generateDocs (package:dartdoc/src/generator/generator_frontend.dart:55:27)
#62     GeneratorFrontEnd.generate (package:dartdoc/src/generator/generator_frontend.dart:21:5)
#63     Dartdoc.generateDocsBase (package:dartdoc/dartdoc.dart:195:23)
<asynchronous suspension>
#64     Dartdoc.generateDocs (package:dartdoc/dartdoc.dart:223:34)
#65     main (file:///project/pkg/pub_dartdoc/bin/pub_dartdoc.dart:32:33)
<asynchronous suspension>
#66     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#67     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by isoos** [comment]
Reproduced and filed https://github.com/dart-lang/dartdoc/issues/2426
