### ISSUE TITLE
OptionsFormatException: Undefined alias / dartdoc

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#4625]
From logs:
```
pub.dartdoc.runner/gql_http_link/0.4.0-nullsafety.1: Error while running dartdoc for gql_http_link 0.4.0-nullsafety.1.
exitCode: 255
stdout: Documenting gql_http_link...
stderr: Unhandled exception:
OptionsFormatException: Undefined alias., <_FileSpan: from <FileLocation: 80 unknown source:5:7> to <FileLocation: 95 unknown source:5:22> "**/*.mocks.dart">
#0      AnalysisOptionsProvider.getOptionsFromString (package:analyzer/src/analysis_options/analysis_options_provider.dart:94:7)
#1      AnalysisOptionsProvider.getOptionsFromSource (package:analyzer/src/analysis_options/analysis_options_provider.dart:64:23)
#2      AnalysisOptionsProvider.getOptionsFromFile (package:analyzer/src/analysis_options/analysis_options_provider.dart:56:12)
#3      ContextLocatorImpl._getExcludedGlobs (package:analyzer/src/dart/analysis/context_locator.dart:295:12)
#4      ContextLocatorImpl.locateRoots (package:analyzer/src/dart/analysis/context_locator.dart:102:28)
#5      new AnalysisContextCollectionImpl (package:analyzer/src/dart/analysis/analysis_context_collection.dart:50:32)
#6      PubPackageBuilder.contextCollection (package:dartdoc/src/model/package_builder.dart:120:28)
#7      PubPackageBuilder.processLibrary (package:dartdoc/src/model/package_builder.dart:155:27)
#8      PubPackageBuilder._parseLibraries (package:dartdoc/src/model/package_builder.dart:214:23)
#9      PubPackageBuilder.getLibraries (package:dartdoc/src/model/package_builder.dart:401:11)
<asynchronous suspension>
#10     PubPackageBuilder.buildPackageGraph (package:dartdoc/src/model/package_builder.dart:70:5)
<asynchronous suspension>
#11     Dartdoc.generateDocsBase (package:dartdoc/dartdoc.dart:183:20)
<asynchronous suspension>
#12     Dartdoc.generateDocs (package:dartdoc/dartdoc.dart:224:28)
<asynchronous suspension>
#13     main (file:///project/pkg/pub_dartdoc/bin/pub_dartdoc.dart:21:19)
<asynchronous suspension>
 
 ```

**Comment by jonasfj** [comment]
Similar:
```
pub.dartdoc.runner/azblob/1.0.3: Error while running dartdoc for azblob 1.0.3.
exitCode: 255
stdout: Documenting azblob...
stderr: Unhandled exception:
OptionsFormatException: Duplicate mapping key., <_FileSpan: from <FileLocation: 207 unknown source:5:1> to <FileLocation: 214 unknown source:5:8> "include">
#0      AnalysisOptionsProvider.getOptionsFromString (package:analyzer/src/analysis_options/analysis_options_provider.dart:94:7)
#1      AnalysisOptionsProvider.getOptionsFromSource (package:analyzer/src/analysis_options/analysis_options_provider.dart:64:23)
#2      AnalysisOptionsProvider.getOptionsFromFile (package:analyzer/src/analysis_options/analysis_options_provider.dart:56:12)
#3      ContextLocatorImpl._getExcludedGlobs (package:analyzer/src/dart/analysis/context_locator.dart:295:12)
#4      ContextLocatorImpl.locateRoots (package:analyzer/src/dart/analysis/context_locator.dart:102:28)
#5      new AnalysisContextCollectionImpl (package:analyzer/src/dart/analysis/analysis_context_collection.dart:50:32)
#6      PubPackageBuilder.contextCollection (package:dartdoc/src/model/package_builder.dart:120:28)
#7      PubPackageBuilder.processLibrary (package:dartdoc/src/model/package_builder.dart:155:27)
#8      PubPackageBuilder._parseLibraries (package:dartdoc/src/model/package_builder.dart:214:23)
#9      PubPackageBuilder.getLibraries (package:dartdoc/src/model/package_builder.dart:401:11)
<asynchronous suspension>
#10     PubPackageBuilder.buildPackageGraph (package:dartdoc/src/model/package_builder.dart:70:5)
<asynchronous suspension>
#11     Dartdoc.generateDocsBase (package:dartdoc/dartdoc.dart:183:20)
<asynchronous suspension>
#12     Dartdoc.generateDocs (package:dartdoc/dartdoc.dart:224:28)
<asynchronous suspension>
#13     main (file:///project/pkg/pub_dartdoc/bin/pub_dartdoc.dart:21:19)
<asynchronous suspension>
```

**Comment by isoos** [comment]
The issue was with `package:analyzer 1.1.0`. Upgrading that to `1.2.0` cleared the problem.
/cc @jcollins-g @srawlins
