### ISSUE TITLE
[search] Link rewrite failed

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#4627]
Stack trace from search service:
```
pub.markdown: Link rewrite failed: src="https://github.com/jcxsoftware-dev/delayed_consumer_hud/raw/master/doc/delayed_consumer_hud_demo.gif"

Error:
    FormatException: Illegal scheme character (at character 4)
    src="https://github.com/jcxsoftware-dev/delayed_consumer_hud/raw/master/doc...
       ^
    

Stack:
    #0      _Uri._fail (dart:core/uri.dart:1538:5)
    #1      _Uri._makeScheme (dart:core/uri.dart:2075:9)
    #2      new _Uri.notSimple (dart:core/uri.dart:1369:18)
    #3      Uri.parse (dart:core/uri.dart:956:17)
    #4      _RelativeUrlRewriter._rewriteAbsoluteUrl (package:pub_dev/shared/markdown.dart:252:21)
    #5      _RelativeUrlRewriter._rewriteUrl (package:pub_dev/shared/markdown.dart:240:18)
    #6      _RelativeUrlRewriter.visitElementAfter (package:pub_dev/shared/markdown.dart:226:11)
    #7      Element.accept (package:markdown/src/ast.dart:52:15)
    #8      Element.accept (package:markdown/src/ast.dart:49:17)
    #9      _rewriteRelativeUrls.<anonymous closure> (package:pub_dev/shared/markdown.dart:81:32)
    #10     List.forEach (dart:core-patch/growable_array.dart:403:8)
    #11     _rewriteRelativeUrls (package:pub_dev/shared/markdown.dart:81:9)
    #12     markdownToHtml (package:pub_dev/shared/markdown.dart:52:11)
    #13     compactReadme (package:pub_dev/search/text_utils.dart:44:16)
    #14     SearchBackend.loadDocument (package:pub_dev/search/backend.dart:167:15)
    <asynchronous suspension>
    #15     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart)
    <asynchronous suspension>
```

**Comment by isoos** [comment]
This seems to be a user input that is wrong and we should handle it somewhat differently:

````
![Demo](src="https://github.com/jcxsoftware-dev/delayed_consumer_hud/raw/master/doc/delayed_consumer_hud_demo.gif")
````

Note: it doesn't display the image on GitHub either.
