### ISSUE TITLE
dartdoc failed: NoSuchMethodError: The getter 'element' was called on null

### ISSUE THREAD

**Issue by Dinesh-DK** [dart-lang/pub-dev#4677]
When trying to run dartdoc in our library [syncfusion_flutter_charts](https://pub.dev/packages/syncfusion_flutter_charts) the dartdoc generation task  fails with a dartdoc internal error message. Also this doesn't occur with the older versions of dartdoc(other than 0.40.0). I have attached the error log below.

`used dartdoc version : 0.40.0`

[flutter_charts_dartdoc.txt](https://github.com/dart-lang/pub-dev/files/6221119/flutter_charts_dartdoc.txt)

```Documenting syncfusion_flutter_charts...

dartdoc failed: NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      new ElementType.from (package:dartdoc/src/element_type.dart:29:11)
#2      new Extension (package:dartdoc/src/model/extension.dart:21:21)
#3      ModelElement._from (package:dartdoc/src/model/model_element.dart:330:14)
#4      new ModelElement.from (package:dartdoc/src/model/model_element.dart:278:40)
#5      Library.extensions.<anonymous closure> (package:dartdoc/src/model/library.dart:202:34)
#6      MappedIterator.moveNext (dart:_internal/iterable.dart:389:20)
#7      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:198:26)
#8      new _List._ofOther (dart:core-patch/array.dart:106:43)
#9      new _List.of (dart:core-patch/array.dart:57:18)
#10     new List.of (dart:core-patch/array_patch.dart:52:20)
#11     Iterable.toList (dart:core/iterable.dart:366:12)
#12     Library.extensions (package:dartdoc/src/model/library.dart:203:10)
#13     Library.modelElementsMap (package:dartdoc/src/model/library.dart:607:17)
#14     Library.allModelElements (package:dartdoc/src/model/library.dart:647:33)
#15     PackageGraph.allModelElements.<anonymous closure>.<anonymous closure> (package:dartdoc/src/model/package_graph.dart:915:48)
#16     SetMixin.forEach (dart:collection/set.dart:142:30)
#17     PackageGraph.allModelElements.<anonymous closure> (package:dartdoc/src/model/package_graph.dart:914:18)
#18     SetMixin.forEach (dart:collection/set.dart:142:30)
#19     PackageGraph.allModelElements (package:dartdoc/src/model/package_graph.dart:908:52)
#20     PackageGraph.precacheLocalDocs.sync_op (package:dartdoc/src/model/package_graph.dart:121:19)
#21     _SyncIterator.moveNext (dart:core-patch/core_patch.dart:181:26)
#22     Future.wait (dart:async/future.dart:393:26)
#23     PackageGraph.initializePackageGraph (package:dartdoc/src/model/package_graph.dart:73:18)
#24     PubPackageBuilder.buildPackageGraph (package:dartdoc/src/model/package_builder.dart:72:20)
<asynchronous suspension>
#25     Dartdoc.generateDocsBase (package:dartdoc/dartdoc.dart:182:20)
<asynchronous suspension>
#26     Dartdoc.generateDocs (package:dartdoc/dartdoc.dart:223:28)
<asynchronous suspension>
#27     Dartdoc.executeGuarded.<anonymous closure> (package:dartdoc/dartdoc.dart:500:9)
<asynchronous suspension>

Program returned code  : 255

**Comment by Dinesh-DK** [comment]
this is further opened in  dartdoc repo
