### ISSUE TITLE
In categories definition for Main, "..." resolves to the missing ...

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#4739]
```
pub.dartdoc.runner/flutter_sound/7.5.2+1: Error while running dartdoc for flutter_sound 7.5.2+1.
exitCode: 255
stdout: Documenting flutter_sound...
Initialized dartdoc with 707 libraries in 98.8 seconds
stderr: Unhandled exception:
In categories definition for Main, "markdown" resolves to the missing file /tmp/pub-dartlang-dartdocYSBGUP/doc/pages/tau-api/main.md
#0      CategoryConfiguration.fromYamlMap (package:dartdoc/src/dartdoc_options.dart:104:13)
#1      _DartdocFileOption._valueAtFromFile (package:dartdoc/src/dartdoc_options.dart:1201:38)
#2      _DartdocFileOption._valueAtFromFilesFirstFound (package:dartdoc/src/dartdoc_options.dart:1140:15)
#3      _DartdocFileOption._valueAtFromFiles (package:dartdoc/src/dartdoc_options.dart:1128:28)
#4      _DartdocFileOption.valueAt (package:dartdoc/src/dartdoc_options.dart:1114:12)
#5      DartdocOptionContext.categories (package:dartdoc/src/dartdoc_options.dart:1481:31)
#6      Category.categoryDefinition (package:dartdoc/src/model/category.dart:163:14)
#7      Category.name (package:dartdoc/src/model/category.dart:103:22)
#8      Package.categories.<anonymous closure> (package:dartdoc/src/model/package.dart:341:58)
#9      WhereIterator.moveNext (dart:_internal/iterable.dart:436:13)
#10     new _GrowableList._ofOther (dart:core-patch/growable_array.dart:198:26)
#11     new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#12     new List.of (dart:core-patch/array_patch.dart:50:28)
#13     Iterable.toList (dart:core/iterable.dart:366:12)
#14     Package.categories (package:dartdoc/src/model/package.dart:341:72)
#15     Package.documentedCategories (package:dartdoc/src/model/package.dart:350:7)
#16     Package.hasDocumentedCategories (package:dartdoc/src/model/package.dart:361:39)
#17     _Renderer_Package.propertyMap.<anonymous closure>.<anonymous closure> (package:dartdoc/src/generator/templates.renderers.dart:1235:41)
#18     RendererBase.section (package:dartdoc/src/mustachio/renderer_base.dart:225:40)
#19     RendererBase.renderBlock (package:dartdoc/src/mustachio/renderer_base.dart:204:9)
#20     RendererBase.section (package:dartdoc/src/mustachio/renderer_base.dart:227:9)
#21     RendererBase.renderBlock (package:dartdoc/src/mustachio/renderer_base.dart:204:9)
#22     _render_Package (package:dartdoc/src/generator/templates.renderers.dart:860:12)
#23     _Renderer_TemplateData.propertyMap.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dartdoc/src/generator/templates.renderers.dart:11324:32)
#24     MappedListIterable.elementAt (dart:_internal/iterable.dart:411:31)
```

**Comment by jonasfj** [comment]
This seems to affect other packages too:
```
pub.dartdoc.runner/flauto/6.4.3+24: Error while running dartdoc for flauto 6.4.3+24.
exitCode: 255
stdout: Documenting flauto...
Initialized dartdoc with 724 libraries in 111.4 seconds
stderr: Unhandled exception:
In categories definition for Amazing, "markdown" resolves to the missing file /tmp/pub-dartlang-dartdocHLOFBY/doc/flutter_sound/flutter_sound_on_web.md
#0      CategoryConfiguration.fromYamlMap (package:dartdoc/src/dartdoc_options.dart:104:13)
#1      _DartdocFileOption._valueAtFromFile (package:dartdoc/src/dartdoc_options.dart:1201:38)
#2      _DartdocFileOption._valueAtFromFilesFirstFound (package:dartdoc/src/dartdoc_options.dart:1140:15)
#3      _DartdocFileOption._valueAtFromFiles (package:dartdoc/src/dartdoc_options.dart:1128:28)
#4      _DartdocFileOption.valueAt (package:dartdoc/src/dartdoc_options.dart:1114:12)
#5      DartdocOptionContext.categories (package:dartdoc/src/dartdoc_options.dart:1481:31)
#6      Category.categoryDefinition (package:dartdoc/src/model/category.dart:163:14)
#7      Category.name (package:dartdoc/src/model/category.dart:103:22)
#8      Package.categories.<anonymous closure> (package:dartdoc/src/model/package.dart:341:58)
#9      WhereIterator.moveNext (dart:_internal/iterable.dart:436:13)
#10     new _GrowableList._ofOther (dart:core-patch/growable_array.dart:198:26)
```

**Comment by isoos** [comment]
They seem to be from the same author, and looks like the issue is documentation outside of the package, which is now being fixed:
https://github.com/Canardoux/tau/commit/f35eb3d080cdbec4f7d98f75473eb43cca9e1f35#diff-6ce269e5b8f3f8b793fd7fed1b5ba6f3a720e0a2cd0b7b18d1c0b0f17e14e454

I'm a bit torn if this should be a `dartdoc` issue, or should we lower the log level by classifying it a client-provided data issue. wdyt?

**Comment by jonasfj** [comment]
> or should we lower the log level by classifying it a client-provided data issue. wdyt?

I'm okay with this. Are we able to signal to the user how to fix this issue?

From the perspective of `dartdoc` I can see that it makes sense for it to fail, if it's configured to use files it cannot find.

**Comment by isoos** [comment]
> Are we able to signal to the user how to fix this issue?

They get the error message and the exception in the dartdoc report section.
