### ISSUE TITLE
Redis exception

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dev#4751]
```
Error:
    Bad state: StreamSink is bound to a stream

Stack:
    #0      _StreamSinkImpl._controller (dart:io/io_sink.dart:216:7)
    #1      _StreamSinkImpl.add (dart:io/io_sink.dart:136:5)
    #2      _Socket.add (dart:io-patch/socket_patch.dart:2019:38)
    #3      Connection.send (package:dartis/src/client/connection.dart:101:13)
    #4      DispatcherBase.send (package:dartis/src/client/dispatcher.dart:29:17)
    #5      _ClientDispatcher.dispatch (package:dartis/src/client/client.dart:199:5)
    #6      Client.run (package:dartis/src/client/client.dart:171:50)
    #7      ModuleBase.execute (package:dartis/src/command/module.dart:57:20)
    #8      ModuleBase.run (package:dartis/src/command/module.dart:50:12)
    #9      Commands.get (package:dartis/src/command/commands.dart:1146:27)
    #10     RedisCacheProvider.get.<anonymous closure> (package:neat_cache/src/providers/redis.dart:145:68)
    #11     RedisCacheProvider._withRedis (package:neat_cache/src/providers/redis.dart:115:22)
    <asynchronous suspension>
    #12     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart)
    <asynchronous suspension>
```

**Comment by isoos** [comment]
This no longer happens.
