### ISSUE TITLE
pub publish dry-run have a hint?

### ISSUE THREAD

**Issue by xieyezi** [dart-lang/pub-dev#4844]
When I finish  migrate my packages to null-safety. I run `dart pub publish --dry-run`, and then I got this hint:

```
Package validation found the following hint:
* You're about to publish a package that opts into null safety.
  The previous version (1.0.1) isn't opted in.
```
`The previous version (1.0.1) isn't opted in.` 

So how can I resolve this hint ?

**Comment by isoos** [comment]
@xieyezi This hint will go away once you publish the package with a null-safe version.

**Comment by xieyezi** [comment]
@isoos But I publish failed, this is my publish log:

```
➜  xyz-city-picker git:(master) dart pub publish
Publishing xyz_city_picker 2.0.0-nullsafety.0 to https://pub.flutter-io.cn:
|-- .gitignore
|-- .metadata
|-- .vscode
|   '-- launch.json
|-- CHANGELOG.md
|-- LICENSE
|-- README.md
|-- example
|   |-- .gitignore
|   |-- .metadata
|   |-- README.md
|   |-- android
|   |   |-- .gitignore
|   |   |-- app
|   |   |   |-- build.gradle
|   |   |   '-- src
|   |   |       |-- debug
|   |   |       |   '-- AndroidManifest.xml
|   |   |       |-- main
|   |   |       |   |-- AndroidManifest.xml
|   |   |       |   |-- kotlin
|   |   |       |   |   '-- com
|   |   |       |   |       '-- example
|   |   |       |   |           '-- example
|   |   |       |   |               '-- MainActivity.kt
|   |   |       |   '-- res
|   |   |       |       |-- drawable
|   |   |       |       |   '-- launch_background.xml
|   |   |       |       |-- mipmap-hdpi
|   |   |       |       |   '-- ic_launcher.png
|   |   |       |       |-- mipmap-mdpi
|   |   |       |       |   '-- ic_launcher.png
|   |   |       |       |-- mipmap-xhdpi
|   |   |       |       |   '-- ic_launcher.png
|   |   |       |       |-- mipmap-xxhdpi
|   |   |       |       |   '-- ic_launcher.png
|   |   |       |       |-- mipmap-xxxhdpi
|   |   |       |       |   '-- ic_launcher.png
|   |   |       |       '-- values
|   |   |       |           '-- styles.xml
|   |   |       '-- profile
|   |   |           '-- AndroidManifest.xml
|   |   |-- build.gradle
|   |   |-- gradle
|   |   |   '-- wrapper
|   |   |       '-- gradle-wrapper.properties
|   |   |-- gradle.properties
|   |   '-- settings.gradle
|   |-- ios
|   |   |-- .gitignore
|   |   |-- Flutter
|   |   |   |-- .last_build_id
|   |   |   |-- AppFrameworkInfo.plist
|   |   |   |-- Debug.xcconfig
|   |   |   '-- Release.xcconfig
|   |   |-- Runner
|   |   |   |-- AppDelegate.swift
|   |   |   |-- Assets.xcassets
|   |   |   |   |-- AppIcon.appiconset
|   |   |   |   |   |-- Contents.json
|   |   |   |   |   |-- Icon-App-1024x1024@1x.png
|   |   |   |   |   |-- Icon-App-20x20@1x.png
|   |   |   |   |   | (10 more...)
|   |   |   |   |   |-- Icon-App-76x76@1x.png
|   |   |   |   |   |-- Icon-App-76x76@2x.png
|   |   |   |   |   '-- Icon-App-83.5x83.5@2x.png
|   |   |   |   '-- LaunchImage.imageset
|   |   |   |       |-- Contents.json
|   |   |   |       |-- LaunchImage.png
|   |   |   |       |-- LaunchImage@2x.png
|   |   |   |       |-- LaunchImage@3x.png
|   |   |   |       '-- README.md
|   |   |   |-- Base.lproj
|   |   |   |   |-- LaunchScreen.storyboard
|   |   |   |   '-- Main.storyboard
|   |   |   |-- Info.plist
|   |   |   '-- Runner-Bridging-Header.h
|   |   |-- Runner.xcodeproj
|   |   |   |-- project.pbxproj
|   |   |   |-- project.xcworkspace
|   |   |   |   |-- contents.xcworkspacedata
|   |   |   |   '-- xcshareddata
|   |   |   |       |-- IDEWorkspaceChecks.plist
|   |   |   |       '-- WorkspaceSettings.xcsettings
|   |   |   '-- xcshareddata
|   |   |       '-- xcschemes
|   |   |           '-- Runner.xcscheme
|   |   '-- Runner.xcworkspace
|   |       |-- contents.xcworkspacedata
|   |       '-- xcshareddata
|   |           |-- IDEWorkspaceChecks.plist
|   |           '-- WorkspaceSettings.xcsettings
|   |-- lib
|   |   |-- main.dart
|   |   '-- xyz_city_picker_example_page.dart
|   |-- pubspec.yaml
|   '-- test
|       '-- widget_test.dart
|-- lib
|   |-- data
|   |   |-- city.dart
|   |   |-- county.dart
|   |   |-- data.dart
|   |   |-- province.dart
|   |   '-- town.dart
|   |-- src
|   |   |-- city_picker.dart
|   |   '-- xyz_city_picker.dart
|   '-- xyz_city_picker.dart
|-- pubspec.yaml
|-- screenshot
|   '-- example.png
'-- test
    '-- xyz_address_picker_test.dart
Package validation found the following hint:
* You're about to publish a package that opts into null safety.
  The previous version (1.0.1) isn't opted in.
  See https://dart.dev/null-safety/migration-guide for best practices.

Publishing is forever; packages cannot be unpublished.
Policy details are available at https://pub.dev/policy


Package has 0 warnings and 1 hint... Do you want to publish xyz_city_picker 2.0.0-nullsafety.0 (y/N)? y
Uploading... 
Failed to upload the package.
```

**Comment by xieyezi** [comment]
and this is my verbose:

```
Package has 0 warnings and 1 hint... Do you want to publish xyz_city_picker 2.0.0-nullsafety.0 (y/N)? y
FINE: Loading OAuth2 credentials.
FINE: Saving OAuth2 credentials.
IO  : Writing 1376 characters to text file /Users/xieyezi/.fvm/versions/2.2.0-stable/.pub-cache/credentials.json.
MSG : Uploading...
IO  : HTTP GET https://pub.flutter-io.cn/api/packages/versions/new
    | Accept: application/vnd.pub.v2+json
    | authorization: <censored>
    | user-agent: Dart pub 2.13.0
IO  : HTTP response 200 OK for GET https://pub.flutter-io.cn/api/packages/versions/new
    | took 0:00:00.100036
    | connection: keep-alive
    | cache-control: 
    | date: Mon, 31 May 2021 12:18:41 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding,Accept-Encoding
    | ali-swift-global-savetime: 1622463521
    | strict-transport-security: max-age=5184000,max-age=31536000; preload
    | age: 473
    | content-type: application/json; charset="utf-8"
    | x-xss-protection: 1; mode=block
    | x-swift-cachetime: 1800
    | server: Tengine
    | timing-allow-origin: *
    | alt-svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
    | content-length: 934
    | x-swift-savetime: Mon, 31 May 2021 12:18:41 GMT
    | x-frame-options: SAMEORIGIN
    | via: 1.1 google, cache22.l2nu20-1[607,607,200-0,M], cache5.l2nu20-1[608,0], cache5.cn44[0,0,200-0,H], cache9.cn44[2,0]
    | x-content-type-options: nosniff
    | x-cache: HIT TCP_MEM_HIT dirn:9:452215262
    | eagleid: 7d4cf79d16224639943632630e
IO  : HTTP POST https://storage.flutter-io.cn
    | authorization: <censored>
    | content-type: multipart/form-data; boundary=dart-http-boundary-b+2UOqcpct7OCmeqeVKT2esZV4Z_cCU+fp8AB5j9uBr3p9ofDX0
    | user-agent: Dart pub 2.13.0
IO  : HTTP response 413 Request Entity Too Large for POST https://storage.flutter-io.cn
    | took 0:00:00.533849
    | connection: close
    | content-type: text/html
    | date: Mon, 31 May 2021 12:26:34 GMT
    | content-length: 598
    | server: Tengine/2.3.2
FINE: Uploading finished (0.664s).
FINE: Saving OAuth2 credentials.
IO  : Writing 1376 characters to text file /Users/xieyezi/.fvm/versions/2.2.0-stable/.pub-cache/credentials.json.
ERR : Failed to upload the package.
FINE: Exception type: ApplicationException
FINE: package:pub/src/utils.dart 512:5                                                      fail
    | package:pub/src/command/lish.dart 109:9                                               LishCommand._publish
    | ===== asynchronous gap ===========================
    | dart:async                                                                            Future.catchError
    | package:pub/src/utils.dart 113:52                                                     captureErrors.wrappedCallback
    | package:stack_trace                                                                   Chain.capture
    | package:pub/src/utils.dart 126:11                                                     captureErrors
    | package:pub/src/command.dart 164:13                                                   PubCommand.run
    | package:args/command_runner.dart 196:27                                               CommandRunner.runCommand
    | package:pub/src/command_runner.dart 150:26                                            PubCommandRunner.runCommand
    | package:pub/src/command_runner.dart 138:18                                            PubCommandRunner.run
    | /opt/s/w/ir/cache/builder/src/third_party/dart/third_party/pkg/pub/bin/pub.dart 9:48  main
[+13959 ms] "flutter pub" took 14,148ms.
[   +6 ms] pub finished with exit code 1
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:366:7)
           <asynchronous suspension>
           #2      PackagesPassthroughCommand.runCommand (package:flutter_tools/src/commands/packages.dart:267:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +259 ms] ensureAnalyticsSent: 255ms
[   +3 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
➜  xyz-city-picker git:(master) 
```

**Comment by xieyezi** [comment]
I got this, I use proxy in china,  So I should change server to `https://pub.dartlang.org` , and then , it's publish successful!
