### ISSUE TITLE
Class 'GrpcError' has no instance method 'asApiResponse'.

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#4859]
```
pub: Handling request: https://pub.dartlang.org/api/packages/file_picker_platform_interface
pub: Request handler failed

Error:
    NoSuchMethodError: Class 'GrpcError' has no instance method 'asApiResponse'.
    Receiver: Instance of 'GrpcError'
    Tried calling: asApiResponse()

Stack:
    dart:core-patch/object_patch.dart 54:5                 Object.noSuchMethod
    package:pub_dev/frontend/handlers/pubapi.g.dart 20:16  _$PubApiRouter.<fn>
    package:stack_trace/src/stack_zone_specification.dart  StackZoneSpecification._registerUnaryCallback.<fn>
     
pub: Request handler done.
```

**Comment by isoos** [comment]
The related code block:
```dart
    try {
       // ... calling the remote endpoint
    } on ApiResponseException catch (e) {
      return e.asApiResponse();
    } catch (e, st) {
      return $utilities.unhandledError(e, st);
    }
```

The related exception is in our API generator:
https://github.com/dart-lang/pub-dev/blob/master/pkg/api_builder/lib/api_builder.dart#L51-L76

The referenced `GrpcError` seems to be in `package:grpc`.

I fail to see how these could be related. I don't see any `ApiResponseException` in our dependencies either. /cc @jonasfj

**Comment by jonasfj** [comment]
We don't see how this can happen.. But we can't reproduce either.

**Comment by jonasfj** [comment]
This reappeared.

**Comment by isoos** [comment]
This still happened with the `20210713t112200` (last week's) release, not yet with this week's.

**Comment by jonasfj** [comment]
The code in question:
https://github.com/dart-lang/pub-dev/blob/8b2899ccaec870622d254b7c1555a11f0e20a84e/app/lib/frontend/handlers/pubapi.g.dart#L19-L21

How can `e` on line 20 be an instance of `GrpcError`?

**Comment by isoos** [comment]
This still happened after the runtime SDK and the dependencies upgrade in `20210728t125700`.

**Comment by jonasfj** [comment]
This happened again.. just a few rare cases.

**Comment by cskau-g** [comment]
Since the try block affect is in an async function, this could well be an async try-index issue (in the VM).
Of course it would be a lot easier to debug if we had a mini repro. case. Though I'm guessing it should be consistently failing if we otherwise set it up right - have you tried always throwing a `GrpcError` from `service.listVersions`?

**Comment by isoos** [comment]
throwing `GrpcError` resulted in a stack trace that is expected:
```
2022-01-03T15:15:19.968752 [SEVERE] api_builder: Unhandled error in API handler (incidentId: 81f04d08-67b1-4046-b374-1b51bbd16008) gRPC Error (code: 1, codeName: CANCELLED, message: null, details: null, rawResponse: null, trailers: {}) #0      listVersionsHandler (package:pub_dev/frontend/handlers/package.dart:383:3)
#1      PubApi.listVersions (package:pub_dev/frontend/handlers/pubapi.dart:38:18)
```

**Comment by isoos** [comment]
I don't think we have seen this stack trace recently.
