### ISSUE TITLE
"delete-old-jobs" -> Error while decoding entity

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#4929]
```

neat_periodic_task: ### [FAILED] neat-periodic-task: "delete-old-jobs"

Error:
    Bad state: Error while decoding entity (Bad state: Error trying to set property "null" to null for field "attemptCount": type 'Null' is not a subtype of type 'int' of 'value', #0      _ModelDescription._decodeProperty (package:gcloud/src/db/model_db_impl.dart:489:7)
    #1      _ModelDescription.decodeEntity.<anonymous closure> (package:gcloud/src/db/model_db_impl.dart:468:7)
    #2      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
    #3      _ModelDescription.decodeEntity (package:gcloud/src/db/model_db_impl.dart:467:34)
    #4      _ExpandoModelDescription.decodeEntity (package:gcloud/src/db/model_db_impl.dart:556:23)
    #5      ModelDBImpl.fromDatastoreEntity (package:gcloud/src/db/model_db_impl.dart:142:31)
    #6      Query.run.<anonymous closure> (package:gcloud/src/db/db.dart:270:41)
    #7      _MapStream._handleData (dart:async/stream_pipe.dart:213:31)
    #8      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
    #9      StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:26)
    #10     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
    #11     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:14)
    #12     _rootRunUnary (dart:async/zone.dart:1362:47)
    #13     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
    #14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
    #15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
    #16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
    #17     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
    #18     _StreamController._add (dart:async/stream_controller.dart:607:7)
    #19     _StreamController.add (dart:async/stream_controller.dart:554:5)
    #20     List.forEach (dart:core-patch/growable_array.dart:403:8)
    #21     StreamFromPages._handlePage (package:gcloud/common.dart:61:16)
    #22     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:26)
    #23     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
    #24     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:14)
    #25     _rootRunUnary (dart:async/zone.dart:1362:47)
    #26     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
    <asynchronous suspension>
    #27     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart)
    <asynchronous suspension>
    ).

Stack:
    #0      ModelDBImpl.fromDatastoreEntity (package:gcloud/src/db/model_db_impl.dart:144:7)
    #1      Query.run.<anonymous closure> (package:gcloud/src/db/db.dart:270:41)
    #2      _MapStream._handleData (dart:async/stream_pipe.dart:213:31)
    #3      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
    #4      StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:26)
    #5      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
    #6      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:14)
    #7      _rootRunUnary (dart:async/zone.dart:1362:47)
    #8      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
    #9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
    #10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
    #11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
    #12     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
    #13     _StreamController._add (dart:async/stream_controller.dart:607:7)
    #14     _StreamController.add (dart:async/stream_controller.dart:554:5)
    #15     List.forEach (dart:core-patch/growable_array.dart:403:8)
    #16     StreamFromPages._handlePage (package:gcloud/common.dart:61:16)
    #17     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:26)
    #18     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
    #19     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:126:14)
    #20     _rootRunUnary (dart:async/zone.dart:1362:47)
    #21     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
    <asynchronous suspension>
    #22     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart)
    <asynchronous suspension>
     
```

**Comment by jonasfj** [comment]
Fixed in #4930
