### ISSUE TITLE
publishing -> type 'Future<ServerResponse?>' is not a subtype of type 'FutureOr<ServerResponse>' in type cast

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#4934]
In version `20210708t193000` prior to traffic migration.

```
pub.cloud_repository: Error post-processing package upload _dummy_pkg/0.0.153+h4to5

Error:
    type 'Future<ServerResponse?>' is not a subtype of type 'FutureOr<ServerResponse>' in type cast

Stack:
    #0      _doAuthXoauth2 (package:mailer/src/smtp/smtp_client.dart:94:7)
    #1      _doAuthentication (package:mailer/src/smtp/smtp_client.dart:104:21)
    #2      connect (package:mailer/src/smtp/smtp_client.dart:137:11)
    <asynchronous suspension>
    #3      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart)
    <asynchronous suspension>
```

**Comment by isoos** [comment]
This looks like an issue in `package:mailer`:
https://github.com/kaisellgren/mailer/blob/master/lib/src/smtp/smtp_client.dart#L93-L94

**Comment by jonasfj** [comment]
See also -> https://github.com/kaisellgren/mailer/issues/175

**Comment by isoos** [comment]
This has been fixed.
