### ISSUE TITLE
dartdoc_runner + protobuf/2.0.0 -> Bad state: T extends GeneratedMessage cannot have parameters

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#4941]
```
pub.dartdoc.runner/protobuf/2.0.0: Error while running dartdoc for protobuf 2.0.0.
exitCode: 255
stdout: Documenting protobuf...
Initialized dartdoc with 43 libraries in 32.2 seconds
Generating docs for library protobuf.meta from package:protobuf/meta.dart...
Generating docs for library protobuf from package:protobuf/protobuf.dart...
stderr:   warning: protobuf has no library level documentation comments
    from protobuf: (file:///tmp/pub-dartlang-dartdocUXOAXH/pkg/lib/protobuf.dart:5:9)
  warning: unresolved doc reference [CodedBufferWritter]
    from protobuf.CodedBufferWriter: (file:///tmp/pub-dartlang-dartdocUXOAXH/pkg/lib/src/protobuf/coded_buffer_writer.dart:20:7)
  warning: unresolved doc reference [mergeFromProto3JSON]
    from protobuf.GeneratedMessage.mergeFromJson: (file:///tmp/pub-dartlang-dartdocUXOAXH/pkg/lib/src/protobuf/generated_message.dart:275:8)
  warning: unresolved doc reference [toProto3JSON]
    from protobuf.GeneratedMessage.writeToJson: (file:///tmp/pub-dartlang-dartdocUXOAXH/pkg/lib/src/protobuf/generated_message.dart:218:10)
  warning: unresolved doc reference [IndexOutOfRangeException]
    from protobuf.FrozenPbList.[]=: (file:///tmp/pub-dartlang-dartdocUXOAXH/pkg/lib/src/protobuf/pb_list.dart:19:17)
    in documentation inherited from protobuf.PbListBase.[]=: (file:///tmp/pub-dartlang-dartdocUXOAXH/pkg/lib/src/protobuf/pb_list.dart:378:17)
  warning: unresolved doc reference [IndexOutOfRangeException]
    from protobuf.PbListBase.[]: (file:///tmp/pub-dartlang-dartdocUXOAXH/pkg/lib/src/protobuf/pb_list.dart:343:14)
  warning: unresolved doc reference [IndexOutOfRangeException]
    from protobuf.PbListBase.[]=: (file:///tmp/pub-dartlang-dartdocUXOAXH/pkg/lib/src/protobuf/pb_list.dart:378:17)
Unhandled exception:
Bad state: T extends GeneratedMessage cannot have parameters
#0      ModelElement.parameters (package:dartdoc/src/model/model_element.dart:980:7)
#1      TypeParameter.referenceChildren (package:dartdoc/src/model/type_parameter.dart:75:23)
#2      DefinedElementType.referenceChildren (package:dartdoc/src/element_type.dart:367:20)
[...]
#14     InlineParser.parse (package:markdown/src/inline_parser.dart:108:9)
#15     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_processor.dart:1111:67)
#16     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_processor.dart:1116:9)
#17     MarkdownDocument.parseMarkdownText (package:dartdoc/src/markdown_processor.dart:1101:5)
#18     Documentation._parseDocumentation (package:dartdoc/src/model/documentation.dart:73:21)
#19     Documentation._renderDocumentation (package:dartdoc/src/model/documentation.dart:48:23)
#20     Documentation.asOneLiner (package:dartdoc/src/model/documentation.dart:40:7)
#21     ModelElement.oneLineDoc (package:dartdoc/src/model/model_element.dart:926:43)
#22     _renderExtension_partial_callable_6 (package:dartdoc/src/generator/templates.aot_renderers_for_html.dart:4690:25)
#23     renderExtension (package:dartdoc/src/generator/templates.aot_renderers_for_html.dart:4226:24)
#24     HtmlAotTemplates.renderExtension (package:dartdoc/src/generator/templates.dart:143:7)
#25     DartdocGeneratorBackend.generateExtension (package:dartdoc/src/generator/dartdoc_generator_backend.dart:171:29)
#26     GeneratorFrontEnd._generateDocs (package:dartdoc/src/generator/generator_frontend.dart:122:29)
#27     GeneratorFrontEnd.generate (package:dartdoc/src/generator/generator_frontend.dart:21:5)
#28     Dartdoc.generateDocsBase (package:dartdoc/dartdoc.dart:213:21)
<asynchronous suspension>
#29     Dartdoc.generateDocs (package:dartdoc/dartdoc.dart:249:28)
<asynchronous suspension>
#30     main (file:///project/pkg/pub_dartdoc/bin/pub_dartdoc.dart:22:19)
<asynchronous suspension>
```

**Comment by jonasfj** [comment]
hmm, I can't reproduce this locally with `dartdoc` version `0.44.0`, but with `1.0.0` this does reproduce
```bash
PACKAGE=protobuf
VERSION=2.0.0

cd $(mktemp -d)
curl -L "https://storage.googleapis.com/pub-packages/packages/$PACKAGE-$VERSION.tar.gz" | tar -xz
dart pub global activate dartdoc
dartdoc
```

**Comment by jonasfj** [comment]
Filed -> https://github.com/dart-lang/dartdoc/issues/2716

**Comment by jonataslaw** [comment]
Does this issue affect a ton of packages, any fix forecasts?

**Comment by isoos** [comment]
The issue was fixed in dartdoc, but we don't know it when it will hit pub.dev (first dartdoc gets a new release, then pub-dev upgrades).

**Comment by jonataslaw** [comment]
> The issue was fixed in dartdoc, but we don't know it when it will hit pub.dev (first dartdoc gets a new release, then pub-dev upgrades).

Thanks for the info!

**Comment by isoos** [comment]
This has been fixed with the current release.
