### ISSUE TITLE
Hosting pub.dev in private App engine

### ISSUE THREAD

**Issue by Kiruel** [dart-lang/pub-dev#5657]
Hi,

I'm looking to host my own pub.dev with App engine and following this [documentation](https://github.com/dart-lang/pub-dev/blob/master/doc/appengine.md). I know the doc is not complete but I try atleast to build in local with this command from the doc:
```bash
cd app
dart pub get
export GCLOUD_PROJECT=<gcloud-project>
export GCLOUD_KEY=<path-to-service-account-key.json>
dart bin/server.dart default
```

When I set this env I got this first problem:
```bash
➜  app git:(master) dart bin/server.dart default
Unhandled exception:
Bad state: Expected environment variable GOOGLE_CLOUD_PROJECT to be set!
#0      _initializeAppEngine._findEnvironmentVariable (package:appengine/src/appengine_internal.dart:140:7)
#1      _initializeAppEngine (package:appengine/src/appengine_internal.dart:145:21)
<asynchronous suspension>
#2      _withAppEngineServicesInternal.<anonymous closure> (package:appengine/src/appengine_internal.dart:102:45)
<asynchronous suspension>
#3      startIsolates (package:pub_dev/service/entrypoint/_isolate.dart:66:3)
<asynchronous suspension>
#4      DefaultCommand.run (package:pub_dev/service/entrypoint/frontend.dart:41:5)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#6      main (file:///pub-dev/app/bin/server.dart:18:3)
<asynchronous suspension>
```

Then when I replace the `GCLOUD_PROJECT` by `GOOGLE_CLOUD_PROJECT`, I got this another problem:
```bash
➜  app git:(master) dart bin/server.dart default
Unhandled exception:
SocketException: Failed host lookup: 'metadata.google.internal' (OS Error: nodename nor servname provided, or not known, errno = 8)
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:682:35)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1817:26)
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
#3      Socket._startConnect (dart:io-patch/socket_patch.dart:2038:22)
#4      Socket.startConnect (dart:io/socket.dart:792:21)
#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2440:18)
#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2834:12)
#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2839:12)
#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2698:12)
#9      _HttpClient.openUrl (dart:_http/http_impl.dart:2570:7)
#10     IOClient.send (package:http/src/io_client.dart:35:38)
#11     RefCountedClient.send (package:googleapis_auth/src/http_client_base.dart:49:23)
#12     BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:38)
#13     BaseClient.get (package:http/src/base_client.dart:27:7)
#14     MetadataServerAuthorizationFlow._getScopes (package:googleapis_auth/src/oauth2_flows/metadata_server.dart:89:36)
#15     MetadataServerAuthorizationFlow.run (package:googleapis_auth/src/oauth2_flows/metadata_server.dart:69:9)
#16     clientFromFlow (package:googleapis_auth/src/oauth2_flows/base_flow.dart:27:36)
#17     clientViaMetadataServer (package:googleapis_auth/src/metadata_server_client.dart:43:11)
#18     clientViaApplicationDefaultCredentials (package:googleapis_auth/auth_io.dart:91:16)
<asynchronous suspension>
#19     _obtainStorageService (package:appengine/src/appengine_internal.dart:237:22)
<asynchronous suspension>
#20     _initializeAppEngine (package:appengine/src/appengine_internal.dart:175:26)
<asynchronous suspension>
#21     _withAppEngineServicesInternal.<anonymous closure> (package:appengine/src/appengine_internal.dart:102:45)
<asynchronous suspension>
#22     startIsolates (package:pub_dev/service/entrypoint/_isolate.dart:66:3)
<asynchronous suspension>
#23     DefaultCommand.run (package:pub_dev/service/entrypoint/frontend.dart:41:5)
<asynchronous suspension>
#24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#25     main (file://pub-dev/app/bin/server.dart:18:3)
<asynchronous suspension>
```

Anyone can help me with that? I can make a PR for the wrong env if needed.

**Comment by isoos** [comment]
The documentation is really outdated. We've recently migrated from using `GCLOUD_KEY` (and the downloaded key) to service accounts, and with that, the service is only running inside the AppEngine environment. We have a local in-memory server for local development, but that is certainly not for production use.

I'm curious: pub-dev was designed for running as a public repository, and not really suitable for private use (e.g. no authorizations for downloads). Why would you run that, instead of one of the community pub servers available? The API required for a server is really narrow, and could be implemented easily, if nothing fits your requirements...

**Comment by jonasfj** [comment]
See also https://medium.com/dartlang/hosting-a-private-dart-package-repository-774c3c51dff9

**Comment by jonasfj** [comment]
it should be able to run with application-default-credentials and a `app/config/<project-id>.yaml` file.

If you're interested in figuring out how, and improve the documentation we're happy to take PRs.

We're also happy to take tweaks that make it easier to run.. But we do focus on running the service on pub.dev and won't promise forward compatibility.

**Comment by jonasfj** [comment]
There are also community efforts like:
https://github.com/themisir/courier

which implements our specification:
https://github.com/dart-lang/pub/blob/master/doc/repository-spec-v2.md

**Comment by sigurdm** [comment]
Closing this as inactive

@Kiruel please open a new issue if you still need assistance.
