### ISSUE TITLE
pana report exceeded size threshold (44735 > 16384)

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#6228]
```
pub.scorecard.backend: pana report exceeded size threshold (44735 > 16384)

Error:
    Exception: pana report exceeded size threshold (44735 > 16384)

Stack:
    #0      LoggerExt.reportError (package:pub_dev/shared/utils.dart:372:53)
    #1      ScoreCardBackend.updateReportOnCard.<anonymous closure>.reportIsTooBig (package:pub_dev/scorecard/backend.dart:217:19)
    #2      ScoreCardBackend.updateReportOnCard.<anonymous closure> (package:pub_dev/scorecard/backend.dart:228:11)
    <asynchronous suspension>
    #3      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:124:15)
    <asynchronous suspension>
```

**Comment by jonasfj** [comment]
We can probably start by augmenting the log to include package/version

**Comment by isoos** [comment]
This is coming from `horizontal_calendar_and_datepicker 0.0.2`, from the URL verification, where we include the entire data URL into the report:

```
<details>
<summary>
Links in `README.md` should be secure. 2 image links are insecure.
</summary>

`README.md:5:1`

```
  ╷
5 │ <img src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/
````
