### ISSUE TITLE
FormatException: Filter error, bad data

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#6327]
Any ideas? @isoos 
```
pub: Handling request: https://pub.dartlang.org/api/packages/firebase_core
api_builder: Unhandled error in API handler (incidentId: xxx)

Error:
    FormatException: Filter error, bad data

Stack:
    #0      _FilterImpl.processed (dart:io-patch/filter_patch.dart:12:69)
    #1      _FilterSink.addSlice (dart:io/data_transformer.dart:505:29)
    #2      _FilterSink.add (dart:io/data_transformer.dart:489:5)
    #3      ZLibDecoder.convert (dart:io/data_transformer.dart:363:9)
    #4      Codec.decode (dart:convert/codec.dart:26:34)
    #5      listVersionsHandler (package:pub_dev/frontend/handlers/package.dart:405:32)
    <asynchronous suspension>
    #6      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:124:15)
    <asynchronous suspension>
```

**Comment by isoos** [comment]
The root cause of this is the same as #6328: bad data returned from redis / network.
