### ISSUE TITLE
Error on pub.dev score analyzing - Unable to locate an Android SDK. Failed to resolve dependencies.

### ISSUE THREAD

**Issue by thruthesky** [dart-lang/pub-dev#6372]
Good day.

I encountered this error out of sudden. I have no clue except the messages in Score tab in pub.dev

When I test on my computer, there is no problem on the dependencies. `flutter pub get` and `flutter analyze` work as expected.

Please, help.

URL: https://pub.dev/packages/fireflow/versions/0.0.91/score

```
stdout: [  +23 ms] Unable to locate an Android SDK.
[   +4 ms] executing: uname -m
[   +4 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +1 ms] executing: [/tool/stable/flutter/] git -c log.showSignature=false log[...]
[   +5 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] b06b8b2710955028a6b562f5aa6fe62941d6febf
[        ] executing: [/tool/stable/flutter/] git tag --points-at b06b8b27109550[...]
[  +31 ms] Exit code 0 from: git tag --points-at b06b8b2710955028a6b562f5aa6fe62941d6febf
[        ] 3.7.0
[  +12 ms] executing: [/tool/stable/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] HEAD
[        ] executing: [/tool/stable/flutter/] git rev-parse --abbrev-ref --symbo[...]
[   +4 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] fatal: HEAD does not point to a branch
[  +28 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, s[...]
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,[...]
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[...]
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skip[...]
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skip[...]
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, ski[...]
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, ski[...]
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +85 ms] executing: /tool/stable/flutter/bin/cache/dart-sdk/bin/dart __depreca[...]
MSG : Resolving dependencies...
MSG : Logs written to /tmp/tool-envXBMEJO/pub-cache-dirOIIMAQ/log/pub_log.txt.
[+4340 ms] "flutter pub" took 4,487ms.
[   +2 ms] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[   +2 ms] exiting with code 1

stderr: FINE: Pub 2.19.0
SLVR: fact: fireflow is 0.0.91
SLVR: derived: fireflow
FINE: Using https://pub.dev instead of https://pub.dartlang.org.
SLVR: fact: fireflow depends on another_flushbar ^1.12.29
SLVR: fact: fireflow depends on built_value 8.4.0
SLVR: fact: fireflow depends on cached_network_image 3.2.1
SLVR: fact: fireflow depends on chewie 1.3.4
SLVR: fact: fireflow depends on cloud_firestore 4.2.0
SLVR: fact: fireflow depends on cloud_firestore_platform_interface 5.9.1
SLVR: fact: fireflow depends on cloud_firestore_web 3.1.1
SLVR: fact: fireflow depends on cloud_functions 4.0.6
SLVR: fact: fireflow depends on cloud_functions_platform_interface 5.1.25
SLVR: fact: fireflow depends on cloud_functions_web 4.3.14
SLVR: fact: fireflow depends on collection 1.16.0
SLVR: fact: fireflow depends on file_picker 4.5.1
SLVR: fact: fireflow depends on firebase_auth 4.2.0
SLVR: fact: fireflow depends on firebase_auth_platform_interface 6.11.4
SLVR: fact: fireflow depends on firebase_auth_web 5.2.0
SLVR: fact: fireflow depends on firebase_core 2.4.0
[...]
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src[...]
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:[...]
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src[...]
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/ru[...]
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_[...]
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src[...]
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
```

**Comment by thruthesky** [comment]
I fixed by removing the collection package. And I think it's not my problem.
I don't close this issue by myself because Dart team would like to see it.

**Comment by isoos** [comment]
@thruthesky: Flutter SDK pins package dependency versions, including `package:collection`. If you try to set a different version range, it will fail like did at your package. If your local setup succeeded, it means that you may be using different, non-stable Flutter version, maybe on beta or master channel. There is not much we can do about it: you may need to follow the pinned versions, or try `dependency_overrides` in the `pubspec.yaml`.

However, `pub` shouldn't throw exception on this operation. /cc @sigurdm was this the bug that has been fixed recently, or a new one?

**Comment by thruthesky** [comment]
Hi, @isoos Thank you for your comment. But I don't use beta or master channel. I always use the stable version.

% flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.6, on macOS 13.0.1 22A400 darwin-arm, locale en-PH)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.74.3)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

**Comment by isoos** [comment]
> But I don't use beta or master channel. I always use the stable version

My bad. The version mismatch may happen whenever you are using an incompatible version constraint compared to the pinned version from the SDK. So you may start with a good constraint on an SDK, but as the SDK upgrades (which on pub.dev does), it may differ.

**Comment by thruthesky** [comment]
@isoos Thank you. I will try to update the constraint. :)

**Comment by sigurdm** [comment]
I think you see the stack-trace (which here is from flutter_tool not pub) because of `--verbose`. I think that is working as intended.
