### ISSUE TITLE
dartdoc on pub failed with unhandled exception

### ISSUE THREAD

**Issue by Zekfad** [dart-lang/pub-dev#6378]
URL: https://pub.dev/packages/nhentai/score

I've build docs locally without problems, but pub.dev version fails with unhandled exception.
Not sure if its bug with dartdoc or pub.dev version of dartdoc though.

<details>
<summary>Log from the site</summary>

```log
exitCode: 255
stdout: [2023-01-29T18:46:29.263278] Starting...
Documenting nhentai...
Initialized dartdoc with 263 libraries
Generating docs for library nhentai from package:nhentai/nhentai.dart...
Generating docs for library nhentai_before_add_cookies from package:nhentai/befo[...]
Generating docs for library nhentai_functions from package:nhentai/functions.dart...
Generating docs for library nhentai_data_model from package:nhentai/data_model.dart...
Generating docs for library nhentai_data_model_prefixed from package:nhentai/dat[...]
Generating docs for library nhentai_prefixed from package:nhentai/nhentai_prefix[...]

stderr: Unhandled exception:
Null check operator used on a null value
#0      ModelElement.parameters.<anonymous closure> (package:dartdoc/src/model/m[...]
#1      ModelElement.parameters (package:dartdoc/src/model/model_element.dart:895:4)
#2      ModelElement.parameters (package:dartdoc/src/model/model_element.dart)
#3      FunctionTypedef.referenceChildren (package:dartdoc/src/model/typedef.dart:133:31)
#4      CommentReferable.referenceBy (package:dartdoc/src/model/comment_referabl[...]
#5      _getMatchingLinkElement (package:dartdoc/src/markdown_processor.dart:226:30)
#6      getMatchingLinkElement (package:dartdoc/src/markdown_processor.dart:238:16)
#7      MarkdownDocument._makeLinkNode (package:dartdoc/src/markdown_processor.d[...]
#8      new MarkdownDocument.withElementLinkResolver.<anonymous closure> (packag[...]
#9      LinkSyntax._resolveReferenceLink (package:markdown/src/inline_syntaxes/l[...]
#10     LinkSyntax._tryCreateReferenceLink (package:markdown/src/inline_syntaxes[...]
#11     LinkSyntax.close (package:markdown/src/inline_syntaxes/link_syntax.dart:89:12)
#12     InlineParser._linkOrImage (package:markdown/src/inline_parser.dart:158:31)
#13     InlineParser.parse (package:markdown/src/inline_parser.dart:114:9)
#14     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_proce[...]
#15     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_proce[...]
#16     MarkdownDocument.parseMarkdownText (package:dartdoc/src/markdown_process[...]
#17     Documentation._parseDocumentation (package:dartdoc/src/model/documentati[...]
#18     Documentation._renderDocumentation (package:dartdoc/src/model/documentat[...]
#19     Documentation.asOneLiner (package:dartdoc/src/model/documentation.dart:54:5)
#20     ModelElement.oneLineDoc (package:dartdoc/src/model/model_element.dart:816:49)
#21     _deduplicated_lib_templates_html__typedef_html (package:dartdoc/src/gene[...]
#22     _renderLibrary_partial_typedef_10 (package:dartdoc/src/generator/templat[...]
#23     renderLibrary (package:dartdoc/src/generator/templates.aot_renderers_for[...]
#24     HtmlAotTemplates.renderLibrary (package:dartdoc/src/generator/templates.[...]
#25     GeneratorBackendBase.generateLibrary (package:dartdoc/src/generator/gene[...]
#26     GeneratorFrontEnd._generateDocs (package:dartdoc/src/generator/generator[...]
#27     GeneratorFrontEnd.generate (package:dartdoc/src/generator/generator_fron[...]
#28     Dartdoc.generateDocsBase (package:dartdoc/src/dartdoc.dart:178:21)
<asynchronous suspension>
#29     Dartdoc.generateDocs (package:dartdoc/src/dartdoc.dart:220:24)
<asynchronous suspension>
#30     pubDartDoc (package:pub_dartdoc/pub_dartdoc.dart:32:19)
<asynchronous suspension>
#31     main (file:///project/pkg/pub_dartdoc/bin/pub_dartdoc.dart:7:52)
<asynchronous suspension>
```

</details>

**Comment by isoos** [comment]
`pub.dev` is on `dartdoc 6.1.1` and the exception happens in that version. We can't upgrade to `6.1.5` yet for various reasons right now, but once a new dartdoc release happens, we may upgrade and the issue will be fixed on our side (no need for new release, we will re-generate the docs).
