### ISSUE TITLE
Sometimes the documentation isn't generated properly generated.

### ISSUE THREAD

**Issue by Lyokone** [dart-lang/pub-dev#6489]
With latest version of cloud_firestore, we ended up not having any documentation available on pub.dev: https://pub.dev/documentation/cloud_firestore/latest/

Whereas for the previous version everything was working fine: https://pub.dev/documentation/cloud_firestore/4.4.3/.

I can see in the logs the following:
- Failed to resolve dependencies.

```
stdout: [  +26 ms] Unable to locate an Android SDK.
[   +4 ms] executing: uname -m
[   +4 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +1 ms] executing: [/tool/stable/flutter/] git -c log.showSignature=false log[...]
[   +5 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] b4bce91dd0f168179d46a7ae5eceb3572ba9637a
[        ] executing: [/tool/stable/flutter/] git tag --points-at b4bce91dd0f168[...]
[  +30 ms] Exit code 0 from: git tag --points-at b4bce91dd0f168179d46a7ae5eceb3572ba9637a
[        ] 3.7.4
[  +12 ms] executing: [/tool/stable/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] HEAD
[        ] executing: [/tool/stable/flutter/] git rev-parse --abbrev-ref --symbo[...]
[   +4 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] fatal: HEAD does not point to a branch
[  +24 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, s[...]
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,[...]
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[...]
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skip[...]
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skip[...]
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, ski[...]
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, ski[...]
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +82 ms] executing: /tool/stable/flutter/bin/cache/dart-sdk/bin/dart __depreca[...]
MSG : Resolving dependencies...
MSG : Logs written to /tmp/tool-envBFFMSR/pub-cache-dirZWQZCR/log/pub_log.txt.
[+2444 ms] "flutter pub" took 2,602ms.
[   +4 ms] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

stderr: FINE: Pub 2.19.2
SLVR: fact: cloud_firestore is 4.4.4
SLVR: derived: cloud_firestore
FINE: Using https://pub.dev instead of https://pub.dartlang.org.
SLVR: fact: cloud_firestore depends on cloud_firestore_platform_interface ^5.11.4
SLVR: fact: cloud_firestore depends on cloud_firestore_web ^3.3.4
SLVR: fact: cloud_firestore depends on collection ^1.0.0
SLVR: fact: cloud_firestore depends on firebase_core ^2.7.1
SLVR: fact: cloud_firestore depends on firebase_core_platform_interface ^4.5.3
SLVR: fact: cloud_firestore depends on flutter from sdk
SLVR: fact: cloud_firestore depends on meta ^1.3.0
SLVR:   selecting cloud_firestore
SLVR:   derived: meta ^1.3.0
SLVR:   derived: flutter from sdk
SLVR:   derived: firebase_core_platform_interface ^4.5.3
SLVR:   derived: firebase_core ^2.7.1
SLVR:   derived: collection ^1.0.0
SLVR:   derived: cloud_firestore_web ^3.3.4
SLVR:   derived: cloud_firestore_platform_interface ^5.11.4
IO  : Get versions from https://pub.dev/api/packages/cloud_firestore_platform_interface.
[...]
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src[...]
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:[...]
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src[...]
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/ru[...]
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_[...]
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src[...]
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
```

Is it because we published cloud_firestore_platform_interface just before? Is there any way to get the documentation automatically retrying after a couple of minutes?

Thanks for your help.

**Comment by Lyokone** [comment]
Thanks for the explanation. When publishing all the updates for FlutterFire we often end up publishing a lot of packages in a short period of time. Do you think a cooldown between each package being published would help? If so, any idea if it should be 10s or a minute? (it's probably something we can implement on our end)

**Comment by isoos** [comment]
I think a minute would be fine. This race condition seems to be rare though, so you may be fine with a few seconds too.

**Comment by sigurdm** [comment]
(Btw, dartdoc seems to be regenerated now for the given package).

**Comment by sigurdm** [comment]
Do we want to change anything here? Or should we close?

**Comment by sigurdm** [comment]
Closing for now.

Maybe this will occur less frequently with our new job queueing system.
It will probably never go away completely.
