### ISSUE TITLE
''flutter pub publish'' and ''flutter pub login'', ERR : 信号灯超时时间已到 after Authorization received, processing for long time

### ISSUE THREAD

**Issue by wl1395182472** [dart-lang/pub-dev#6676]
URL: https://pub.dev/

run
```
flutter pub publish
```
or
```
flutter pub login
```

<details><summary>flutter pub publish -v</summary>

```
PS E:\github\cache_string> flutter packages pub publish -v
[   +3 ms] executing: [E:\flutter-sdk/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +57 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] d3d8effc686d73e0114d71abdcccef63fa1f25d2
[        ] executing: [E:\flutter-sdk/] git tag --points-at d3d8effc686d73e0114d71abdcccef63fa1f25d2
[  +71 ms] Exit code 0 from: git tag --points-at d3d8effc686d73e0114d71abdcccef63fa1f25d2
[        ] 3.10.1
[   +2 ms] executing: [E:\flutter-sdk/] git rev-parse --abbrev-ref HEAD
[  +47 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
.......
.......
IO  : Spawning "cmd /c git rev-parse --show-toplevel" in E:\github\cache_string\.
IO  : Finished git. Exit code 0.
    | stdout:
    | | E:/github/cache_string
    | Nothing output on stderr.
IO  : Reading binary file E:\github\cache_string\README.md.
IO  : Read 51 bytes from E:\github\cache_string\README.md.
IO  : Reading binary file E:\github\cache_string\CHANGELOG.md.
IO  : Read 31 bytes from E:\github\cache_string\CHANGELOG.md.
IO  : Spawning "E:\flutter-sdk\bin\cache\dart-sdk\bin\dart.exe analyze --fatal-infos .\lib .\pubspec.yaml" in E:\github\cache_string\.
IO  : Get versions from https://pub.dev/api/packages/cache_string.
IO  : HTTP GET https://pub.dev/api/packages/cache_string
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: windows
    | X-Pub-Command: publish
    | X-Pub-Session-ID: C82F51C9-E2DE-472A-913E-443E8867BAF8
    | X-Pub-Environment: flutter_cli:passthrough
    | user-agent: Dart pub 3.0.1
IO  : HTTP response 404 Not Found for GET https://pub.dev/api/packages/cache_string
    | took 0:00:00.710795
    | x-powered-by: Dart with package:shelf
    | cache-control: public, max-age=0
    | transfer-encoding: chunked
    | date: Sat, 20 May 2023 04:13:47 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding
    | strict-transport-security: max-age=31536000; preload
    | via: 1.1 google
    | content-type: application/json; charset="utf-8"
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
IO  : Finished E:\flutter-sdk\bin\cache\dart-sdk\bin\dart.exe. Exit code 0.
    | stdout:
    | | Analyzing lib, pubspec.yaml...
    | | No issues found!
    | Nothing output on stderr.
FINE: Validating package finished (1.710s).
MSG :
    | Publishing is forever; packages cannot be unpublished.
    | Policy details are available at https://pub.dev/policy
FINE: Showing confirm message:
    | Do you want to publish cache_string 0.0.1 to https://pub.dev
FINE: Loading OAuth2 credentials.
MSG : Pub needs your authorization to upload packages on your behalf.
    | In a web browser, go to https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&response_type=code&client_id=818368855108-8grd2eg9tj9f38os6f1urbcvsq399u8n.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A61755&code_challenge=wTiPbBs6D7d9trtPuMV-d-Of-0vRUVBfbUxhFTQp70I&code_challenge_method=S256&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email
    | Then click "Allow access".
    |
    | Waiting for your authorization...
MSG : Authorization received, processing...
IO  : HTTP POST https://accounts.google.com/o/oauth2/token
    | content-type: application/x-www-form-urlencoded; charset=utf-8
    | user-agent: Dart pub 3.0.1
IO  : HTTP POST https://accounts.google.com/o/oauth2/token
    | content-type: application/x-www-form-urlencoded; charset=utf-8
    | user-agent: Dart pub 3.0.1
IO  : HTTP POST https://accounts.google.com/o/oauth2/token
    | content-type: application/x-www-form-urlencoded; charset=utf-8
    | user-agent: Dart pub 3.0.1
IO  : HTTP POST https://accounts.google.com/o/oauth2/token
    | content-type: application/x-www-form-urlencoded; charset=utf-8
    | user-agent: Dart pub 3.0.1
ERR : 信号灯超时时间已到
FINE: Exception type: _ClientSocketException
FINE: package:http/src/io_client.dart 94:7                   IOClient.send
    | ===== asynchronous gap ===========================
    | dart:async                                             Future.catchError
    | package:pub/src/utils.dart 113:52                      captureErrors.wrappedCallback
    | package:stack_trace                                    Chain.capture
    | package:pub/src/utils.dart 126:11                      captureErrors
    | package:pub/src/command.dart 198:13                    PubCommand.run
    | package:args/command_runner.dart 212:27                CommandRunner.runCommand
    | package:dartdev/dartdev.dart 226:30                    DartdevRunner.runCommand
    | package:args/command_runner.dart 122:25                CommandRunner.run.<fn>
    | dart:async                                             new Future.sync
    | package:args/command_runner.dart 122:14                CommandRunner.run
    | package:dartdev/dartdev.dart 58:29                     runDartdev
    | C:\b\s\w\ir\x\w\sdk\pkg\dartdev\bin\dartdev.dart 11:9  main
---- End log transcript ----
IO  : Writing 89681 characters to text file C:\Users\24563\AppData\Local\Pub\Cache\log\pub_log.txt.
MSG : Logs written to C:\Users\24563\AppData\Local\Pub\Cache\log\pub_log.txt.
[+97934 ms] pub failed
                     command: "E:\flutter-sdk\bin\cache\dart-sdk\bin\dart pub --suppress-analytics publish -v"
                     pub env: {
                       "FLUTTER_ROOT": "E:\flutter-sdk",
                       "PUB_ENVIRONMENT": "flutter_cli:passthrough",
                     }
                     exit code: 69

[   +7 ms] "flutter pub" took 98,070ms.
[   +3 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub._runWithStdioInherited (package:flutter_tools/src/dart/pub.dart:447:7)
           <asynchronous suspension>
           #2      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:530:5)
           <asynchronous suspension>
           #3      PackagesPassthroughCommand.runCommand
(package:flutter_tools/src/commands/packages.dart:153:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1336:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[ +259 ms] ensureAnalyticsSent: 252ms
[   +2 ms] Running 0 shutdown hooks
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 69
```

</details>

<details><summary>flutter doctor -v</summary>

```
PS E:\github\cache_string> flutter doctor -v
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel stable, 3.10.1, on Microsoft Windows [版本 10.0.22621.1555], locale zh-CN)
    • Flutter version 3.10.1 on channel stable at E:\flutter-sdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (3 days ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at E:\android-sdk
    • Platform android-33-ext5, build-tools 33.0.2
    • Java binary at: E:\Program Files\Android\Android Studio2022\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\24563\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.1)
    • Visual Studio at E:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33424.131
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (version 2022.1)
    • Android Studio at E:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 2022.2)
    • Android Studio at E:\Program Files\Android\Android Studio2022
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.22621.1555]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 111.0.5563.111
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 113.0.1774.42

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by sigurdm** [comment]
Some locations (such as China) have trouble connecting to pub.dev

Consider trying a VPN.
