### ISSUE TITLE
pub.task.backend: max size exceeded path: documentation/google_fonts/3.0.1/package.tar.gz

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#6935]
```
pub: Handling request: https://pub.dartlang.org/documentation/google_fonts/3.0.1/package.tar.gz
pub.task.backend: max size exceeded path: 2023.08.17/google_fonts/3.0.1/49ed74cc6289b1387eb85168434eb706.blob

Error:
    Input stream exceeded the maxSize: 10485760

Stack:
    #0      BucketExt.readAsBytes (package:pub_dev/shared/storage.dart:111:7)
    #1      TaskBackend._readFromBucket (package:pub_dev/task/backend.dart:742:28)
    #2      TaskBackend.gzippedTaskResult (package:pub_dev/task/backend.dart:869:14)
    <asynchronous suspension>
    #3      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:127:15)
    <asynchronous suspension>
```

**Comment by isoos** [comment]
This is now fixed.
